import { describe, test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const client = readFileSync(join(__dirname, "../clients/generated/wlt-api.ts"), "utf-8");
const bundle = readFileSync(join(__dirname, "../contracts/generated/wlt.bundle.openapi.yaml"), "utf-8");

function operationIds(source) {
  return [...source.matchAll(/^\s*operationId:\s*([A-Za-z0-9_.-]+)\s*$/gm)].map((match) => match[1]);
}

describe("generated WLT API client provenance", () => {
  test("is generated by openapi-typescript from the committed bundle", () => {
    assert.match(client, /This file was auto-generated by openapi-typescript\./);
    assert.match(bundle, /^# AUTO-GENERATED by tools\/scripts\/compose-wlt-openapi\.mjs\. DO NOT EDIT\./);
    assert.match(bundle, /x-bthwani-contract-layout: BUNDLED_GENERATED/);
    assert.match(bundle, /x-bthwani-source-digest: [a-f0-9]{64}/);
  });

  test("contains every operation declared by the canonical bundle", () => {
    const declared = operationIds(bundle);
    assert.ok(declared.length > 20, "the WLT bundle must include indexed module operations");
    for (const operationId of declared) {
      assert.match(client, new RegExp(`\\b${operationId}\\b`), `generated client is missing ${operationId}`);
    }
  });

  test("does not preserve hand-authored negative route declarations", () => {
    assert.doesNotMatch(client, /post\?:\s*never/);
    assert.doesNotMatch(client, /appendWltLedgerEntry/);
    assert.doesNotMatch(bundle, /^\s*operationId:\s*appendWltLedgerEntry\s*$/m);
    assert.doesNotMatch(bundle, /^\s*post:\s*#.*ledger/m);
  });
});
