package main

import (
	"fmt"
	"os"
)

// DEV SEED ONLY.
// Not valid as closure evidence.
// Must not be used to prove fullstack journey completion.
func main() {
	fmt.Fprintln(os.Stdout, "dev_seed_partner_onboarding: no closure evidence is generated by this command")
	fmt.Fprintln(os.Stdout, "use verify_partner_onboarding_api for API-only journey verification")
}
