package identity

import (
	"context"
	"errors"

	"github.com/lib/pq"
)

// localBootstrapSecurityUsernames is deliberately private and explicit. These
// are the password-authenticated actors owned by the local-development bootstrap.
// Workforce-managed field/captain actors are excluded because they authenticate
// through governed activation codes and must never acquire password semantics.
func localBootstrapSecurityUsernames() []string {
	return []string{
		"operator",
		"bthwani",
		"client",
		"platform-approver",
		"platform-applier",
		"platform-rollout-manager",
	}
}

// ReconcileLocalBootstrapSecurityState completes local bootstrap convergence
// after all canonical local actors have been upserted successfully.
//
// Password hashes are intentionally regenerated by BootstrapLocalActors and
// BootstrapLocalPlatformActors. Failed login-attempt rows from an older local
// credential state must therefore stop participating in the current lockout
// window; otherwise a freshly reconciled local actor can remain locked for up
// to fifteen minutes even though its authoritative credential has changed.
//
// This cleanup is intentionally limited to failed attempts for the exact local
// bootstrap usernames and only runs when IDENTITY_LOCAL_BOOTSTRAP is enabled.
// Successful login history is preserved. Production authentication and the
// global lockout policy are untouched.
func (r *Repository) ReconcileLocalBootstrapSecurityState(ctx context.Context, input LocalBootstrap) error {
	if !input.Enabled {
		return nil
	}
	if r == nil || r.db == nil {
		return errors.New("local identity bootstrap security convergence requires a database")
	}

	_, err := r.db.ExecContext(ctx, `
DELETE FROM identity_login_attempts
WHERE succeeded = false
  AND username = ANY($1)`, pq.Array(localBootstrapSecurityUsernames()))
	return err
}
