package identity

import (
	"context"
	"errors"
	"strings"

	"github.com/lib/pq"
)

// localBootstrapSecurityUsernames is deliberately private and explicit. These
// are the password-authenticated actors owned by the local-development bootstrap.
// Workforce-managed field/captain actors are excluded because they authenticate
// through governed activation codes and must never acquire password semantics.
func localBootstrapSecurityUsernames() []string {
	return []string{
		"operator",
		"bthwani",
		"client",
		"platform-approver",
		"platform-applier",
		"platform-rollout-manager",
	}
}

// LocalBootstrapConverged reports whether every password-authenticated actor
// owned by the local bootstrap is present, ACTIVE, and bound to the active
// operator context.
//
// The runtime supervisor consults this before re-running the bootstrap so a
// healthy runtime is never re-converged. That distinction is load bearing:
// re-running the bootstrap regenerates password hashes and advances updated_at,
// which ReconcileLocalBootstrapSecurityState reads as a new credential epoch and
// uses to discard earlier failed attempts. Re-running it on a timer would
// therefore erase the login rate limit on every tick, so convergence must be
// repaired only when it is genuinely broken.
func (r *Repository) LocalBootstrapConverged(ctx context.Context, input LocalBootstrap) (bool, error) {
	if !input.Enabled {
		return true, nil
	}
	if r == nil || r.db == nil {
		return false, errors.New("local identity bootstrap convergence check requires a database")
	}
	operatorContextID := strings.TrimSpace(input.OperatorContextID)
	if operatorContextID == "" {
		return false, errors.New("BTHWANI_OPERATOR_CONTEXT_ID is required when IDENTITY_LOCAL_BOOTSTRAP=true")
	}

	expected := localBootstrapSecurityUsernames()
	var present int
	if err := r.db.QueryRowContext(ctx, `
SELECT count(*)
FROM identity_actors
WHERE username = ANY($1)
  AND operator_context_id = $2
  AND status = 'ACTIVE'`,
		pq.Array(expected),
		operatorContextID,
	).Scan(&present); err != nil {
		return false, err
	}
	return present == len(expected), nil
}

// ReconcileLocalBootstrapSecurityState completes local bootstrap convergence
// after all canonical local actors have been upserted successfully.
//
// Password hashes are intentionally regenerated by BootstrapLocalActors and
// BootstrapLocalPlatformActors. A failed attempt that predates the actor's
// freshly reconciled updated_at belongs to the previous local credential epoch
// and must not keep the new canonical credential locked. Failed attempts created
// after reconciliation remain untouched, so the normal login rate-limit remains
// fully enforced.
//
// This cleanup is intentionally limited to the exact password-backed actors
// owned by the local bootstrap, the active operator context, and stale failures
// only. Successful login history is preserved. Production authentication and
// the global lockout policy are untouched because this function is a no-op when
// IDENTITY_LOCAL_BOOTSTRAP is disabled.
func (r *Repository) ReconcileLocalBootstrapSecurityState(ctx context.Context, input LocalBootstrap) error {
	if !input.Enabled {
		return nil
	}
	if r == nil || r.db == nil {
		return errors.New("local identity bootstrap security convergence requires a database")
	}
	operatorContextID := strings.TrimSpace(input.OperatorContextID)
	if operatorContextID == "" {
		return errors.New("BTHWANI_OPERATOR_CONTEXT_ID is required when IDENTITY_LOCAL_BOOTSTRAP=true")
	}

	_, err := r.db.ExecContext(ctx, `
DELETE FROM identity_login_attempts AS attempt
USING identity_actors AS actor
WHERE attempt.username = actor.username
  AND attempt.succeeded = false
  AND attempt.created_at <= actor.updated_at
  AND actor.operator_context_id = $2
  AND actor.username = ANY($1)`,
		pq.Array(localBootstrapSecurityUsernames()),
		operatorContextID,
	)
	return err
}
