package http

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"log"
	"net/http"
	"os"
	"strings"

	"identity-api/internal/identity"
)

const selfServiceOtpRequestLimit = 32 * 1024

type OperatorContextOtpRepository interface {
	RequestOtpForOperatorContext(
		ctx context.Context,
		operatorContextID string,
		input identity.OtpInput,
	) (identity.IssueActivationResult, error)
}

func writeOperatorContextOtpError(w http.ResponseWriter, err error) {
	switch {
	case errors.Is(err, identity.ErrOperatorContextMismatch):
		sendError(w, http.StatusForbidden, "OPERATOR_CONTEXT_FORBIDDEN", "phone is already bound to another OperatorContext")
	case errors.Is(err, identity.ErrActivationRateLimited):
		sendError(w, http.StatusTooManyRequests, "ACTIVATION_RATE_LIMITED", "activation can be requested again later")
	case errors.Is(err, identity.ErrInvalidActivation):
		sendError(w, http.StatusBadRequest, "INVALID_REQUEST", "invalid phone or actor type")
	case errors.Is(err, identity.ErrActivationUnavailable):
		sendError(w, http.StatusServiceUnavailable, "ACTIVATION_UNAVAILABLE", "activation is not configured")
	default:
		// The response body stays generic, but an unmapped failure must not be
		// silent: the payload-less 500 previously hid a foreign-key violation on
		// every public OTP request with nothing in the logs to diagnose it.
		log.Printf("[identity-api] unmapped OTP request failure: %v", err)
		sendError(w, http.StatusInternalServerError, "IDENTITY_INTERNAL_ERROR", "identity request failed")
	}
}

func readSelfServiceOtpInput(w http.ResponseWriter, r *http.Request) (identity.OtpInput, bool) {
	body, err := io.ReadAll(io.LimitReader(r.Body, selfServiceOtpRequestLimit+1))
	if err != nil || len(body) > selfServiceOtpRequestLimit {
		sendError(w, http.StatusBadRequest, "INVALID_REQUEST", "request body is invalid")
		return identity.OtpInput{}, false
	}
	r.Body = io.NopCloser(bytes.NewReader(body))

	var input identity.OtpInput
	if json.Unmarshal(body, &input) != nil {
		sendError(w, http.StatusBadRequest, "INVALID_REQUEST", "request body is invalid")
		return identity.OtpInput{}, false
	}
	return input, true
}



// OtpBoundary owns the public phone-verification/consumer bootstrap path.
// Provider and employee access codes are never self-issued: they must be
// generated by the authorised department through the actor-bound internal
// invitation path. Every runtime mode resolves the OperatorContext from explicit server
// configuration; callers cannot select or override it and no legacy default
// OperatorContext path is reachable.
func OtpBoundary(repository OperatorContextOtpRepository, next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost || r.URL.Path != "/auth/otp/request" {
			next.ServeHTTP(w, r)
			return
		}

		request, ok := readSelfServiceOtpInput(w, r)
		if !ok {
			return
		}
		if strings.TrimSpace(request.ActorType) != "client" {
			sendError(
				w,
				http.StatusForbidden,
				"PLATFORM_ACCESS_CODE_REQUIRED",
				"provider and employee access codes are issued only by an authorised platform department",
			)
			return
		}

		operatorContextID := strings.TrimSpace(os.Getenv("BTHWANI_OPERATOR_CONTEXT_ID"))
		if operatorContextID == "" {
			sendError(w, http.StatusServiceUnavailable, "SAAS_RUNTIME_CONFIG_INVALID", "BTHWANI_OPERATOR_CONTEXT_ID is required for OTP requests")
			return
		}

		result, err := repository.RequestOtpForOperatorContext(r.Context(), operatorContextID, request)
		if err != nil {
			writeOperatorContextOtpError(w, err)
			return
		}
		sendJSON(w, http.StatusOK, result)
	})
}
