param(
    [Parameter(Mandatory)][string] $Organization,
    [Parameter(Mandatory)][string] $ClientProject,
    [Parameter(Mandatory)][string] $ClientDsn,
    [Parameter(Mandatory)][string] $PartnerProject,
    [Parameter(Mandatory)][string] $PartnerDsn,
    [Parameter(Mandatory)][string] $CaptainProject,
    [Parameter(Mandatory)][string] $CaptainDsn,
    [Parameter(Mandatory)][string] $FieldProject,
    [Parameter(Mandatory)][string] $FieldDsn,
    [string] $AuthToken = "",
    [ValidateSet("development", "preview", "production")]
    [string] $Environment = "development",
    [ValidateRange(0.0, 1.0)]
    [double] $TracesSampleRate = 0.05,
    [switch] $DebugSdk,
    [switch] $StartupProbe
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "../..")).Path
$TargetDirectory = Join-Path $RepoRoot "infra/local"
$TargetPath = Join-Path $TargetDirectory "mobile.env"

function Assert-NonEmpty {
    param([string] $Name, [string] $Value)
    if ([string]::IsNullOrWhiteSpace($Value)) {
        throw "$Name must not be empty."
    }
}

function Assert-SentryDsn {
    param([string] $Name, [string] $Value)
    Assert-NonEmpty -Name $Name -Value $Value
    $uri = $null
    if (-not [Uri]::TryCreate($Value.Trim(), [UriKind]::Absolute, [ref] $uri) -or
        $uri.Scheme -notin @("http", "https") -or
        [string]::IsNullOrWhiteSpace($uri.Host)) {
        throw "$Name must be an absolute Sentry HTTP(S) DSN."
    }
}

Assert-NonEmpty -Name "Organization" -Value $Organization
foreach ($entry in @(
    @{ Name = "ClientProject"; Value = $ClientProject },
    @{ Name = "PartnerProject"; Value = $PartnerProject },
    @{ Name = "CaptainProject"; Value = $CaptainProject },
    @{ Name = "FieldProject"; Value = $FieldProject }
)) {
    Assert-NonEmpty -Name $entry.Name -Value $entry.Value
}
Assert-SentryDsn -Name "ClientDsn" -Value $ClientDsn
Assert-SentryDsn -Name "PartnerDsn" -Value $PartnerDsn
Assert-SentryDsn -Name "CaptainDsn" -Value $CaptainDsn
Assert-SentryDsn -Name "FieldDsn" -Value $FieldDsn

New-Item -ItemType Directory -Path $TargetDirectory -Force | Out-Null
$ExistingLines = if (Test-Path -LiteralPath $TargetPath -PathType Leaf) {
    @(Get-Content -LiteralPath $TargetPath)
} else {
    @(
        "# Local mobile runtime configuration. This file is ignored by Git.",
        "BTHWANI_AUTO_START_BACKEND=1"
    )
}

$ManagedValues = [ordered]@{
    SENTRY_ORG = $Organization.Trim()
    SENTRY_PROJECT_APP_CLIENT = $ClientProject.Trim()
    EXPO_PUBLIC_SENTRY_DSN_APP_CLIENT = $ClientDsn.Trim()
    SENTRY_PROJECT_APP_PARTNER = $PartnerProject.Trim()
    EXPO_PUBLIC_SENTRY_DSN_APP_PARTNER = $PartnerDsn.Trim()
    SENTRY_PROJECT_APP_CAPTAIN = $CaptainProject.Trim()
    EXPO_PUBLIC_SENTRY_DSN_APP_CAPTAIN = $CaptainDsn.Trim()
    SENTRY_PROJECT_APP_FIELD = $FieldProject.Trim()
    EXPO_PUBLIC_SENTRY_DSN_APP_FIELD = $FieldDsn.Trim()
    EXPO_PUBLIC_APP_ENV = $Environment
    EXPO_PUBLIC_SENTRY_TRACES_SAMPLE_RATE = $TracesSampleRate.ToString([Globalization.CultureInfo]::InvariantCulture)
    EXPO_PUBLIC_SENTRY_DEBUG = $(if ($DebugSdk) { "true" } else { "false" })
    EXPO_PUBLIC_SENTRY_STARTUP_PROBE = $(if ($StartupProbe) { "true" } else { "false" })
}
if (-not [string]::IsNullOrWhiteSpace($AuthToken)) {
    $ManagedValues["SENTRY_AUTH_TOKEN"] = $AuthToken.Trim()
}

$ManagedNames = @($ManagedValues.Keys)
$PreservedLines = foreach ($line in $ExistingLines) {
    $match = [regex]::Match([string] $line, "^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=")
    if (-not $match.Success -or $ManagedNames -notcontains $match.Groups[1].Value) {
        [string] $line
    }
}

$Output = New-Object System.Collections.Generic.List[string]
foreach ($line in $PreservedLines) { $Output.Add($line) }
if ($Output.Count -gt 0 -and -not [string]::IsNullOrWhiteSpace($Output[$Output.Count - 1])) {
    $Output.Add("")
}
$Output.Add("# Governed Sentry configuration generated by configure-mobile-sentry.ps1")
foreach ($entry in $ManagedValues.GetEnumerator()) {
    $Output.Add("$($entry.Key)=$($entry.Value)")
}

Set-Content -LiteralPath $TargetPath -Value $Output -Encoding utf8NoBOM

Write-Host "Sentry local configuration written: $TargetPath"
Write-Host "Organization: $($Organization.Trim())"
Write-Host "Projects: $($ClientProject.Trim()), $($PartnerProject.Trim()), $($CaptainProject.Trim()), $($FieldProject.Trim())"
Write-Host "Startup probe: $(if ($StartupProbe) { 'enabled for the next launches' } else { 'disabled' })"
Write-Host "No DSN or token value was printed."
