export declare const brandRoots: {
    readonly brandAction: "#FF500D";
    readonly surfaceBase: "#FFFFFF";
    readonly brandStructure: "#0A2F5C";
};
export type BrandRoot = keyof typeof brandRoots;
export declare function alpha(hex: string, opacity: number): string;
export declare const brandScale: {
    readonly action: {
        readonly 50: "#FFF3ED";
        readonly 100: "#FFE2D4";
        readonly 200: "#FFC0A3";
        readonly 300: "#FF9A6B";
        readonly 400: "#FF7138";
        readonly 500: "#FF500D";
        readonly 600: "#E5480C";
        readonly 700: "#B73809";
        readonly 800: "#8C2B07";
        readonly 900: "#641F05";
    };
    readonly structure: {
        readonly 50: "#EEF5FC";
        readonly 100: "#D8E7F7";
        readonly 200: "#B4CFEA";
        readonly 300: "#86AED8";
        readonly 400: "#4E83BD";
        readonly 500: "#275F96";
        readonly 600: "#0A2F5C";
        readonly 700: "#082744";
        readonly 800: "#061D33";
        readonly 900: "#041322";
    };
    readonly surface: {
        readonly 0: "#FFFFFF";
        readonly 50: "#FFFCF8";
        readonly 100: "#F8F5F0";
        readonly 200: "#EFE9E0";
        readonly 300: "#E3DACE";
        readonly 400: "#D2C7B8";
    };
};
export declare const colorRoles: {
    readonly brandAction: "#FF500D";
    readonly brandActionHover: "#E5480C";
    readonly brandActionPressed: "#B73809";
    readonly brandActionSoft: "#FFF3ED";
    readonly brandActionTint: string;
    readonly surfaceBase: "#FFFFFF";
    readonly surfaceWarm: "#FFFCF8";
    readonly surfaceMuted: "#F8F5F0";
    readonly surfaceInset: "#EFE9E0";
    readonly surfaceOverlay: string;
    readonly mediaScrimStrong: string;
    readonly brandStructure: "#0A2F5C";
    readonly brandStructureElevated: "#275F96";
    readonly brandStructureSoft: "#EEF5FC";
    readonly brandStructureTint: string;
    readonly textPrimary: "#0A2F5C";
    readonly textSecondary: "#275F96";
    readonly textMuted: string;
    readonly textInverse: "#FFFFFF";
    readonly textOnMediaMuted: string;
    readonly textOnMediaStrong: string;
    readonly borderSubtle: string;
    readonly borderStrong: string;
    readonly focusRing: string;
    readonly success: "#1F8B4C";
    readonly warning: "#B96A06";
    readonly danger: "#C43B35";
    readonly info: "#295FAA";
    readonly shadowBase: "#000000";
};
export type ColorRole = keyof typeof colorRoles;
export declare const neutralScale: {
    readonly 0: "#FFFFFF";
    readonly 50: "#F8FAFC";
    readonly 100: "#F1F5F9";
    readonly 200: "#E2E8F0";
    readonly 300: "#CBD5E1";
    readonly 400: "#94A3B8";
    readonly 500: "#64748B";
    readonly 600: "#475569";
    readonly 700: "#334155";
    readonly 800: "#1E293B";
    readonly 900: "#0F172A";
    readonly 950: "#020617";
};
export declare const statusScale: {
    readonly successSoft: "#ECFDF3";
    readonly success: "#1F8B4C";
    readonly successStrong: "#16653A";
    readonly warningSoft: "#FFFBEB";
    readonly warning: "#B96A06";
    readonly warningStrong: "#8E5204";
    readonly dangerSoft: "#FEF2F2";
    readonly danger: "#C43B35";
    readonly dangerStrong: "#9B2F2B";
    readonly infoSoft: "#EFF6FF";
    readonly info: "#295FAA";
    readonly infoStrong: "#214D89";
};
export declare const lightThemeColors: {
    readonly background: "#FFFCF8";
    readonly backgroundAlt: "#FFFFFF";
    readonly surface: "#FFFFFF";
    readonly surfaceRaised: "#FFFCF8";
    readonly surfaceInset: "#F8F5F0";
    readonly surfaceOverlay: string;
    readonly color: "#0A2F5C";
    readonly colorSecondary: "#275F96";
    readonly colorMuted: string;
    readonly colorInverse: "#FFFFFF";
    readonly borderColor: string;
    readonly borderColorStrong: string;
    readonly focusColor: string;
    readonly action: "#FF500D";
    readonly actionHover: "#E5480C";
    readonly actionPressed: "#B73809";
    readonly actionSoft: "#FFF3ED";
    readonly structure: "#0A2F5C";
    readonly structureSoft: "#EEF5FC";
    readonly success: "#1F8B4C";
    readonly successSoft: "#ECFDF3";
    readonly warning: "#B96A06";
    readonly warningSoft: "#FFFBEB";
    readonly danger: "#C43B35";
    readonly dangerSoft: "#FEF2F2";
    readonly info: "#295FAA";
    readonly infoSoft: "#EFF6FF";
    readonly shadowColor: "#000000";
};
export declare const darkThemeColors: {
    readonly background: "#020617";
    readonly backgroundAlt: "#0F172A";
    readonly surface: "#0F172A";
    readonly surfaceRaised: "#1E293B";
    readonly surfaceInset: "#020617";
    readonly surfaceOverlay: string;
    readonly color: "#F8FAFC";
    readonly colorSecondary: "#E2E8F0";
    readonly colorMuted: "#94A3B8";
    readonly colorInverse: "#0A2F5C";
    readonly borderColor: string;
    readonly borderColorStrong: string;
    readonly focusColor: string;
    readonly action: "#FF500D";
    readonly actionHover: "#FF7138";
    readonly actionPressed: "#FF9A6B";
    readonly actionSoft: string;
    readonly structure: "#F8FAFC";
    readonly structureSoft: "#1E293B";
    readonly success: "#4ADE80";
    readonly successSoft: string;
    readonly warning: "#F5C04E";
    readonly warningSoft: string;
    readonly danger: "#F2877A";
    readonly dangerSoft: string;
    readonly info: "#8BB4E8";
    readonly infoSoft: string;
    readonly shadowColor: "#000000";
};
export declare const tamaguiColorTokens: {
    readonly successSoft: "#ECFDF3";
    readonly success: "#1F8B4C";
    readonly successStrong: "#16653A";
    readonly warningSoft: "#FFFBEB";
    readonly warning: "#B96A06";
    readonly warningStrong: "#8E5204";
    readonly dangerSoft: "#FEF2F2";
    readonly danger: "#C43B35";
    readonly dangerStrong: "#9B2F2B";
    readonly infoSoft: "#EFF6FF";
    readonly info: "#295FAA";
    readonly infoStrong: "#214D89";
    readonly brandAction: "#FF500D";
    readonly brandActionHover: "#E5480C";
    readonly brandActionPressed: "#B73809";
    readonly brandActionSoft: "#FFF3ED";
    readonly brandActionTint: string;
    readonly surfaceBase: "#FFFFFF";
    readonly surfaceWarm: "#FFFCF8";
    readonly surfaceMuted: "#F8F5F0";
    readonly surfaceInset: "#EFE9E0";
    readonly surfaceOverlay: string;
    readonly mediaScrimStrong: string;
    readonly brandStructure: "#0A2F5C";
    readonly brandStructureElevated: "#275F96";
    readonly brandStructureSoft: "#EEF5FC";
    readonly brandStructureTint: string;
    readonly textPrimary: "#0A2F5C";
    readonly textSecondary: "#275F96";
    readonly textMuted: string;
    readonly textInverse: "#FFFFFF";
    readonly textOnMediaMuted: string;
    readonly textOnMediaStrong: string;
    readonly borderSubtle: string;
    readonly borderStrong: string;
    readonly focusRing: string;
    readonly shadowBase: "#000000";
};
export declare const colorPalette: {
    readonly white: "#FFFFFF";
    readonly black: "#000000";
    readonly redMuted: "#E53935";
    readonly orangeMuted: "#F59E0B";
    readonly orangeSoft: "#FFF3E0";
    readonly redSoft: "#FFEBEE";
    readonly yellowSoft: "#FFF8E1";
    readonly greenSoft: "#E6F9F0";
    readonly dangerSoft: "#FEE8E8";
    readonly infoSoft: "#EAF0FB";
    readonly warningSoft: "#FEF6E4";
    readonly graySoft: "#F3F4F6";
    readonly greenStrong: "#0E7A45";
    readonly dangerStrong: "#C0392B";
    readonly warningStrong: "#B45309";
    readonly grayBorder: "#ECECEC";
    readonly tanBg: "#F5ECE3";
};
//# sourceMappingURL=colors.d.ts.map