// Code generated by tools/scripts/generate-openapi-go-types.mjs from OpenAPI. DO NOT EDIT.
// Contract: core/identity/contracts/generated/identity.bundle.openapi.yaml

package identityauth

import "time"

// ActivateRequest defines model for ActivateRequest.
type ActivateRequest struct {
	ActorType         string `json:"actorType"`
	Code              string `json:"code"`
	DeviceFingerprint string `json:"deviceFingerprint,omitempty"`
	Phone             string `json:"phone"`
}

// ActivationChallengeMetadata defines model for ActivationChallengeMetadata.
type ActivationChallengeMetadata struct {
	ActivationID string    `json:"activationId"`
	CreatedAt    time.Time `json:"createdAt"`
	ExpiresAt    time.Time `json:"expiresAt"`
	MaskedPhone  string    `json:"maskedPhone"`
	Status       string    `json:"status"`
}

// ActorAdminView defines model for ActorAdminView.
type ActorAdminView struct {
	ActorID   string   `json:"actorId"`
	Created   bool     `json:"created,omitempty"`
	PhoneE164 string   `json:"phoneE164"`
	Roles     []string `json:"roles"`
	Status    string   `json:"status"`
	Username  string   `json:"username"`
	Version   int      `json:"version"`
}

// ActorIdentity defines model for ActorIdentity.
type ActorIdentity struct {
	AuthState         string          `json:"authState"`
	ExpiresAt         time.Time       `json:"expiresAt"`
	OperatorContextID string          `json:"operatorContextId"`
	Permissions       []Permission    `json:"permissions"`
	PhoneE164         string          `json:"phoneE164"`
	Roles             []string        `json:"roles"`
	ServiceAccess     map[string]bool `json:"serviceAccess"`
	SessionID         string          `json:"sessionId"`
	SessionSurface    string          `json:"sessionSurface"`
	Subject           string          `json:"subject"`
	SurfaceAccess     map[string]bool `json:"surfaceAccess"`
}

// ActorSearchPage defines model for ActorSearchPage.
type ActorSearchPage struct {
	Items      []ActorAdminView `json:"items"`
	Limit      int              `json:"limit"`
	NextCursor string           `json:"nextCursor,omitempty"`
	Total      int              `json:"total"`
}

// ApiError defines model for ApiError.
type ApiError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// EmployeePermissionBundleCode defines model for EmployeePermissionBundleCode.
type EmployeePermissionBundleCode string

// EmployeePermissionBundleDescriptor defines model for EmployeePermissionBundleDescriptor.
type EmployeePermissionBundleDescriptor struct {
	AllowedEmploymentClasses   []string                     `json:"allowedEmploymentClasses"`
	Code                       EmployeePermissionBundleCode `json:"code"`
	DefaultDepartmentScope     string                       `json:"defaultDepartmentScope,omitempty"`
	DepartmentSelectionAllowed bool                         `json:"departmentSelectionAllowed"`
	NameAr                     string                       `json:"nameAr"`
	NameEn                     string                       `json:"nameEn"`
}

// EmployeeProvisionRequest defines model for EmployeeProvisionRequest.
type EmployeeProvisionRequest struct {
	DepartmentScope  string                       `json:"departmentScope"`
	PermissionBundle EmployeePermissionBundleCode `json:"permissionBundle,omitempty"`
	PhoneE164        string                       `json:"phoneE164"`
	Username         string                       `json:"username"`
}

// IntrospectRequest defines model for IntrospectRequest.
type IntrospectRequest struct {
	Token string `json:"token"`
}

// IssueActivationForActorRequest defines model for IssueActivationForActorRequest.
type IssueActivationForActorRequest struct {
	ExpectedActorType string `json:"expectedActorType"`
	ExpectedSurface   string `json:"expectedSurface"`
	IssuedByActorID   string `json:"issuedByActorId"`
}

// IssueActivationResponse defines model for IssueActivationResponse.
type IssueActivationResponse struct {
	ActivationID string    `json:"activationId"`
	Code         string    `json:"code"`
	ExpiresAt    time.Time `json:"expiresAt"`
	MaskedPhone  string    `json:"maskedPhone"`
}

// IssueSupportSessionRequest defines model for IssueSupportSessionRequest.
type IssueSupportSessionRequest struct {
	DurationMinutes  int    `json:"durationMinutes,omitempty"`
	InitiatorActorID string `json:"initiatorActorId"`
	Reason           string `json:"reason"`
	SupportRequestID string `json:"supportRequestId"`
	TargetActorID    string `json:"targetActorId"`
}

// ListAdministrativeEmployeePermissionBundlesResponse defines model for ListAdministrativeEmployeePermissionBundlesResponse.
type ListAdministrativeEmployeePermissionBundlesResponse struct {
	PermissionBundles []EmployeePermissionBundleDescriptor `json:"permissionBundles"`
}

// ListPartnerPermissionBundlesResponse defines model for ListPartnerPermissionBundlesResponse.
type ListPartnerPermissionBundlesResponse struct {
	PermissionBundles []PartnerPermissionBundleDescriptor `json:"permissionBundles"`
}

// ListRBACActorRoleAssignmentsResponse defines model for ListRBACActorRoleAssignmentsResponse.
type ListRBACActorRoleAssignmentsResponse struct {
	Assignments []RbacActorRoleAssignment `json:"assignments"`
}

// ListRBACPermissionVocabularyResponse defines model for ListRBACPermissionVocabularyResponse.
type ListRBACPermissionVocabularyResponse struct {
	Permissions []PermissionVocabularyEntry `json:"permissions"`
}

// ListRBACRolesResponse defines model for ListRBACRolesResponse.
type ListRBACRolesResponse struct {
	Roles []RbacRole `json:"roles"`
}

// ListRBACStaffResponse defines model for ListRBACStaffResponse.
type ListRBACStaffResponse struct {
	Staff []RbacStaffActor `json:"staff"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	DeviceFingerprint string `json:"deviceFingerprint,omitempty"`
	Password          string `json:"password"`
	Username          string `json:"username"`
}

// OtpRequest defines model for OtpRequest.
type OtpRequest struct {
	ActorType string `json:"actorType"`
	Phone     string `json:"phone"`
}

// PartnerActivationRequest defines model for PartnerActivationRequest.
type PartnerActivationRequest struct {
	IssuedByActorID string `json:"issuedByActorId"`
	StoreID         string `json:"storeId"`
}

// PartnerActorProvisionRequest defines model for PartnerActorProvisionRequest.
type PartnerActorProvisionRequest struct {
	PermissionBundle string `json:"permissionBundle"`
	PhoneE164        string `json:"phoneE164"`
	StoreID          string `json:"storeId"`
	Username         string `json:"username"`
}

// PartnerPermissionBundleDescriptor defines model for PartnerPermissionBundleDescriptor.
type PartnerPermissionBundleDescriptor struct {
	Actions []string `json:"actions"`
	Code    string   `json:"code"`
	NameAr  string   `json:"nameAr"`
	NameEn  string   `json:"nameEn"`
}

// PartnerStoreAccessRequest defines model for PartnerStoreAccessRequest.
type PartnerStoreAccessRequest struct {
	Enabled          bool   `json:"enabled"`
	PermissionBundle string `json:"permissionBundle,omitempty"`
	Reactivate       bool   `json:"reactivate"`
	StoreID          string `json:"storeId"`
}

// Permission defines model for Permission.
type Permission struct {
	Action  string `json:"action"`
	Scope   string `json:"scope"`
	Service string `json:"service"`
	Surface string `json:"surface"`
}

// PermissionVocabularyEntry defines model for PermissionVocabularyEntry.
type PermissionVocabularyEntry struct {
	Action      string `json:"action"`
	Description string `json:"description"`
	ID          string `json:"id"`
	Service     string `json:"service"`
	Surface     string `json:"surface"`
}

// ProvisionActorRequest defines model for ProvisionActorRequest.
type ProvisionActorRequest struct {
	OperatorContextID string `json:"operatorContextId,omitempty"`
	PhoneE164         string `json:"phoneE164"`
	Role              string `json:"role"`
	Username          string `json:"username"`
}

// RbacActorRoleAssignment defines model for RbacActorRoleAssignment.
type RbacActorRoleAssignment struct {
	ActorID   string `json:"actorId"`
	GrantedBy string `json:"grantedBy"`
	RoleID    string `json:"roleId"`
	RoleName  string `json:"roleName"`
}

// RbacRole defines model for RbacRole.
type RbacRole struct {
	Active      bool         `json:"active"`
	CreatedAt   time.Time    `json:"createdAt"`
	Description string       `json:"description"`
	ID          string       `json:"id"`
	Name        string       `json:"name"`
	Permissions []Permission `json:"permissions"`
	UpdatedAt   time.Time    `json:"updatedAt"`
	Version     int          `json:"version"`
}

// RbacRoleDefinitionRequest defines model for RbacRoleDefinitionRequest.
type RbacRoleDefinitionRequest struct {
	Active          bool         `json:"active"`
	Description     string       `json:"description"`
	ExpectedVersion int          `json:"expectedVersion"`
	Permissions     []Permission `json:"permissions"`
}

// RbacRoleGrantRequest defines model for RbacRoleGrantRequest.
type RbacRoleGrantRequest struct {
	ExpectedRoleVersion int    `json:"expectedRoleVersion"`
	RequestedByActorID  string `json:"requestedByActorId"`
	RoleName            string `json:"roleName"`
}

// RbacStaffActor defines model for RbacStaffActor.
type RbacStaffActor struct {
	GrantedAt time.Time `json:"grantedAt"`
	ID        string    `json:"id"`
	Roles     []string  `json:"roles"`
	Username  string    `json:"username"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	DeviceFingerprint string `json:"deviceFingerprint,omitempty"`
	RefreshToken      string `json:"refreshToken"`
}

// ResolveActorPermissionsResponse defines model for ResolveActorPermissionsResponse.
type ResolveActorPermissionsResponse struct {
	ActorID     string       `json:"actorId"`
	Permissions []Permission `json:"permissions"`
}

// RuntimeCheckStatus defines model for RuntimeCheckStatus.
type RuntimeCheckStatus struct {
	Critical   bool   `json:"critical"`
	DurationMS int    `json:"durationMs"`
	Name       string `json:"name"`
	ReasonCode string `json:"reasonCode,omitempty"`
	Status     string `json:"status"`
}

// RuntimeStatus defines model for RuntimeStatus.
type RuntimeStatus struct {
	CheckedAt     time.Time            `json:"checkedAt"`
	Checks        []RuntimeCheckStatus `json:"checks"`
	Code          string               `json:"code,omitempty"`
	CorrelationID string               `json:"correlationId"`
	DurationMS    int                  `json:"durationMs"`
	LastSuccessAt *time.Time           `json:"lastSuccessAt,omitempty"`
	Message       string               `json:"message,omitempty"`
	ReasonCodes   []string             `json:"reasonCodes"`
	Service       string               `json:"service"`
	Status        string               `json:"status"`
}

// SessionInfo defines model for SessionInfo.
type SessionInfo struct {
	CompromisedAt     *time.Time `json:"compromisedAt,omitempty"`
	CreatedAt         time.Time  `json:"createdAt"`
	DeviceFingerprint string     `json:"deviceFingerprint"`
	ExpiresAt         time.Time  `json:"expiresAt"`
	LastUsedAt        *time.Time `json:"lastUsedAt,omitempty"`
	SessionID         string     `json:"sessionId"`
	Surface           string     `json:"surface"`
	Version           int        `json:"version"`
}

// SupportSessionIdentity defines model for SupportSessionIdentity.
type SupportSessionIdentity struct {
	AuthState         string       `json:"authState"`
	ExpiresAt         time.Time    `json:"expiresAt"`
	InitiatorActorID  string       `json:"initiatorActorId"`
	OperatorContextID string       `json:"operatorContextId"`
	Permissions       []Permission `json:"permissions"`
	PhoneE164         string       `json:"phoneE164"`
	Roles             []string     `json:"roles"`
	SessionID         string       `json:"sessionId"`
	SessionKind       string       `json:"sessionKind"`
	Subject           string       `json:"subject"`
	SupportRequestID  string       `json:"supportRequestId"`
}

// SupportSessionToken defines model for SupportSessionToken.
type SupportSessionToken struct {
	AccessToken string                 `json:"accessToken"`
	ExpiresIn   int                    `json:"expiresIn"`
	Identity    SupportSessionIdentity `json:"identity"`
	TokenType   string                 `json:"tokenType"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken  string        `json:"accessToken"`
	ExpiresIn    int           `json:"expiresIn"`
	Identity     ActorIdentity `json:"identity"`
	RefreshToken string        `json:"refreshToken"`
	TokenType    string        `json:"tokenType"`
}
