import type { DshCapability } from "./capability-map";

/**
 * Adds operations and surface coverage to an existing canonical DSH capability.
 * Extension entries are never standalone owners.
 */
export type DshCapabilityExtension = {
  readonly id: DshCapability["id"];
  readonly status: DshCapability["status"];
  readonly contractOperations: readonly string[];
  readonly surfaces: readonly string[];
  readonly runtimeBound: boolean;
  readonly closureState: DshCapability["closureState"];
  readonly topic?: DshCapability["topic"];
  readonly topicScope: readonly string[];
};

export const DSH_CAPABILITY_MAP_EXTENSIONS = [
  {
    id: "dsh.client.catalog",
    status: "runtime-verified",
    contractOperations: [
      "listPartnerProductProposals",
      "listFieldProductProposals",
      "listOperatorCatalogAttributes",
      "createOperatorCatalogAttribute",
      "listOperatorCatalogAttributeOptions",
      "createOperatorCatalogAttributeOption",
      "upsertOperatorCatalogNodeAttributeRule",
      "listOperatorMasterProductAttributeValues",
      "upsertOperatorMasterProductAttributeValue",
      "listOperatorMasterProductRelationships",
      "upsertOperatorMasterProductRelationship",
      "deleteOperatorMasterProductRelationship",
      "listOperatorAssortmentPauses",
      "pauseOperatorStoreAssortment",
      "resumeOperatorStoreAssortment",
      "listOperatorCatalogAudit",
      "rollbackOperatorCatalogAudit",
      "listPartnerCatalogAttributes",
      "listPartnerCatalogAttributeOptions",
      "listPartnerMasterProductAttributeValues",
      "listPartnerMasterProductRelationships",
      "get_dsh_partner_stores__storeId__assortment_pauses",
      "post_dsh_partner_stores__storeId__assortment__masterProductId__pause",
      "post_dsh_partner_stores__storeId__assortment__masterProductId__resume",
      "listFieldCatalogAttributes",
      "listFieldCatalogAttributeOptions",
      "listFieldMasterProductAttributeValues",
      "listFieldMasterProductRelationships",
      "get_dsh_field_partners__partnerId__assortment_pauses",
      "post_dsh_field_partners__partnerId__assortment__masterProductId__pause",
      "post_dsh_field_partners__partnerId__assortment__masterProductId__resume",
    ],
    surfaces: ["app-client", "app-partner", "app-field", "control-panel"],
    runtimeBound: true,
    closureState: "IMPLEMENTED_MULTI_SURFACE",
    topic: "catalog",
    topicScope: [
      "partner-proposal-readback",
      "field-proposal-readback",
      "product-attributes",
      "category-attribute-rules",
      "product-alternatives",
      "assortment-pauses",
      "catalog-audit",
      "guarded-rollback",
    ],
  },
  {
    id: "dsh.support.hub",
    status: "experience-fix-required",
    contractOperations: [
      "approveDshSpecialRequestQuote",
      "assignDshSpecialRequestDispatch",
      "cancelDshClientSpecialRequest",
      "createDshClientSpecialRequest",
      "getDshClientSpecialRequest",
      "getDshOperatorSpecialRequest",
      "listDshClientSpecialRequests",
      "listDshOperatorSpecialRequests",
      "updateDshOperatorSpecialRequest",
      "getDshOperatorSupportTicket",
      "listDshOperatorSupportMessages",
      "addDshOperatorSupportMessage",
      "listDshOperatorSupportEvents",
    ],
    surfaces: ["app-client", "app-partner", "app-captain", "control-panel"],
    runtimeBound: true,
    closureState: "FIX_REQUIRED",
    topic: "support",
    topicScope: [
      "special-requests",
      "quotes",
      "dispatch-handoff",
      "client-ticket-submission",
      "partner-ticket-submission",
      "captain-ticket-submission",
      "ticket-conversation",
      "operator-readback",
      "support-audit",
    ],
  },
  {
    id: "dsh.notifications",
    status: "experience-fix-required",
    contractOperations: [
      "upsertDshNotificationPushEndpoint",
      "deactivateDshNotificationPushEndpoint",
      "listDshNotificationDeliveryAttempts",
    ],
    surfaces: ["app-client", "app-partner", "app-captain", "app-field", "control-panel"],
    runtimeBound: true,
    closureState: "IMPLEMENTED_MULTI_SURFACE",
    topicScope: [
      "actor-inbox",
      "channel-preferences",
      "quiet-hours",
      "localized-templates",
      "deep-links",
      "actor-targeting",
      "push-endpoint-lifecycle",
      "push-provider-worker",
      "delivery-audit",
      "retry-dead-letter",
    ],
  },
  {
    id: "dsh.client.dispatch",
    status: "experience-fix-required",
    contractOperations: [
      "arriveDshPartnerDeliveryTask",
      "assignDshPartnerDeliveryTask",
      "departDshPartnerDeliveryTask",
      "extendDshPickupWindow",
      "getDshOperatorPartnerDelivery",
      "getDshOperatorPickup",
      "listDshOperatorPartnerDeliveries",
      "listDshOperatorPickups",
      "markDshPartnerDeliveryPickedUp",
      "markDshPickupCustomerArrived",
      "markDshPickupNoShow",
      "markDshPickupReady",
      "notifyDshPickupCustomer",
      "raiseDshPartnerDeliveryException",
      "submitDshPartnerDeliveryProof",
      "verifyDshPickupSession",
    ],
    surfaces: ["control-panel", "app-partner", "app-captain", "app-client"],
    runtimeBound: true,
    closureState: "FIX_REQUIRED",
    topic: "commerce",
    topicScope: ["partner-delivery", "pickup", "proof", "exceptions"],
  },
  {
    id: "dsh.client.checkout",
    status: "experience-fix-required",
    contractOperations: [
      "listDshClientAddresses",
      "createDshClientAddress",
      "updateDshClientAddress",
      "deleteDshClientAddress",
      "setDshClientDefaultAddress",
      "searchDshClientMapLocations",
      "reverseDshClientMapLocation",
    ],
    surfaces: ["app-client"],
    runtimeBound: false,
    closureState: "FIX_REQUIRED",
    topic: "commerce",
    topicScope: [
      "client-address-book",
      "governed-map-search",
      "reverse-geocoding",
      "serviceability-address",
      "checkout-address",
    ],
  },
  {
    id: "dsh.policies",
    status: "experience-fix-required",
    contractOperations: [
      "get_dsh_operator_platform_service_areas",
      "put_dsh_operator_platform_service_areas__serviceAreaCode_",
    ],
    surfaces: ["control-panel"],
    runtimeBound: false,
    closureState: "FIX_REQUIRED",
    topicScope: [
      "service-area-geofences",
      "coordinate-to-service-area",
      "map-provider-boundary",
    ],
  },
] as const satisfies readonly DshCapabilityExtension[];
