import type { DshCapability } from "./capability-map";

export const DSH_CAPABILITY_MAP_EXTENSIONS = [
  {
    id: "dsh.field.finance",
    status: "experience-fix-required",
    contractOperations: [
      "DELETEDshFieldFinancePayoutDestinationsDestinationId",
      "GETDshCaptainFinanceCommissions",
      "GETDshCaptainFinancePayouts",
      "GETDshFieldFinanceCommissions",
      "GETDshFieldFinancePayoutDestinations",
      "GETDshFieldFinancePayouts",
      "GETDshFieldFinanceWallet",
      "PATCHDshFieldFinancePayoutDestinationsDestinationId",
      "POSTDshCaptainFinanceCodRecordsRecordIdCollect",
      "POSTDshCaptainFinanceCodRecordsRecordIdRemit",
      "POSTDshCaptainFinancePayouts",
      "POSTDshFieldFinancePayoutDestinations",
      "POSTDshFieldFinancePayouts",
      "completeDshControlPanelFinancePayoutRequest",
      "createDshGovernedSettlementFromDeliveredOrders",
      "failDshControlPanelFinancePayoutRequest",
      "processDshControlPanelFinancePayoutRequest",
      "upsertDshSettlementPolicy",
    ],
    surfaces: ["app-field", "app-captain", "control-panel"],
    runtimeBound: true,
    closureState: "FIX_REQUIRED",
    topic: "field-ops",
    topicScope: ["field-finance", "captain-finance", "settlements", "payout-processing"],
  },
  {
    id: "dsh.support.hub",
    status: "experience-fix-required",
    contractOperations: [
      "approveDshSpecialRequestQuote",
      "assignDshSpecialRequestDispatch",
      "cancelDshClientSpecialRequest",
      "createDshClientSpecialRequest",
      "getDshClientSpecialRequest",
      "getDshOperatorSpecialRequest",
      "listDshClientSpecialRequests",
      "listDshOperatorSpecialRequests",
      "updateDshOperatorSpecialRequest",
    ],
    surfaces: ["app-client", "control-panel"],
    runtimeBound: true,
    closureState: "FIX_REQUIRED",
    topic: "support",
    topicScope: ["special-requests", "quotes", "dispatch-handoff"],
  },
  {
    id: "dsh.client.dispatch",
    status: "experience-fix-required",
    contractOperations: [
      "arriveDshPartnerDeliveryTask",
      "assignDshPartnerDeliveryTask",
      "departDshPartnerDeliveryTask",
      "extendDshPickupWindow",
      "getDshOperatorPartnerDelivery",
      "getDshOperatorPickup",
      "listDshOperatorPartnerDeliveries",
      "listDshOperatorPickups",
      "markDshPartnerDeliveryPickedUp",
      "markDshPickupCustomerArrived",
      "markDshPickupNoShow",
      "markDshPickupReady",
      "notifyDshPickupCustomer",
      "raiseDshPartnerDeliveryException",
      "submitDshPartnerDeliveryProof",
      "verifyDshPickupSession",
    ],
    surfaces: ["control-panel", "app-partner", "app-captain", "app-client"],
    runtimeBound: true,
    closureState: "FIX_REQUIRED",
    topic: "commerce",
    topicScope: ["partner-delivery", "pickup", "proof", "exceptions"],
  },
] as const satisfies readonly DshCapability[];
