import { DSH_CAPABILITY_MAP } from "./capability-map";
import { DSH_RUNTIME_MAP } from "./runtime-map";
import { DSH_SURFACE_MAP } from "./surface-map";

export const dshServiceManifest = {
  service: "dsh",
  realService: true,
  activatesService: true,
  runtimeState: "PARTIALLY_BOUND",
  closureState: "FIX_REQUIRED",
  activationScope: "stores-home-discovery-catalog-cart-checkout-wlt-handoff-orders-dispatch-field-readiness-support-analytics-notifications",
  contract: "contracts/dsh.openapi.yaml",
  contractState: "CONTRACT_ACTIVE",
  capabilities: DSH_CAPABILITY_MAP,
  surfaces: DSH_SURFACE_MAP,
  runtime: DSH_RUNTIME_MAP,
  currentTruth: {
    contractOperations: [
      "getDshHealth",
      "getDshReadiness",
      "listDshStores",
      "getDshHomeDiscovery",
      "listOperatorHomeDiscoveryContent",
      "createOperatorHomeDiscoveryContent",
      "updateOperatorHomeDiscoveryContent",
      "deleteOperatorHomeDiscoveryContent",
      "getDshStore",
      "getDshStoreContext",
      "listOperatorDshStores",
      "getOperatorDshStore",
      "updatePartnerStoreSettings",
      "submitFieldStoreVerification",
      "reportCaptainPickupReadiness",
      "governDshStore",
      "listDshStoreAudit",
      "getPublishedDshCatalog",
      "getDshClientCart",
      "clearDshClientCart",
      "upsertDshCartItem",
      "removeDshCartItem",
      "checkDshCartServiceability",
      "listOperatorCarts",
      "createDshCheckoutIntent",
      "getDshCheckoutIntent",
      "cancelDshCheckoutIntent",
      "listOperatorCheckoutIntents",
      "createDshOrder",
      "listDshClientOrders",
      "getDshClientOrder",
      "listDshPartnerOrders",
      "acceptDshOrder",
      "rejectDshOrder",
      "markDshOrderPreparing",
      "markDshOrderReadyForPickup",
      "listDshOperatorOrders",
      "cancelDshOperatorOrder",
      "listDshDispatchAssignments",
      "createDshAssignment",
      "listDshCaptainAssignments",
      "acceptDshAssignment",
      "declineDshAssignment",
      "updateDshDeliveryStatus",
      "submitDshPoD",
      "getDshClientOrderTracking",
      "listDshControlPanelFinanceSettlements",
      "getDshControlPanelFinanceSettlementSummary",
      "listDshControlPanelFinanceRefunds",
      "completeAssetUpload",
      "deleteCatalogAsset",
      "acceptDshPartnerInvite",
      "approveDshControlPanelFinancePayoutRequest",
      "assignDshControlPanelFinanceReconciliationCase",
      "executeDshPartnerStoreTeamMemberAction",
      "getDshControlPanelFinanceFinancialSummary",
      "getDshControlPanelFinanceReconciliationCase",
      "getDshPartnerFinanceSettlementSummary",
      "getDshPartnerStoreCourierSettings",
      "getPartnerStoreSettings",
      "getPublicCatalogMedia",
      "getStoreDiagnostics",
      "inviteDshPartnerStoreTeamMember",
      "listDshControlPanelFinancePayoutRequests",
      "listDshControlPanelFinanceReconciliationCases",
      "listDshPartnerFinanceSettlements",
      "listDshPartnerInvites",
      "listDshPartnerScopes",
      "listDshPartnerStoreCoverageZones",
      "listDshPartnerStoreTeam",
      "listPublicReels",
      "listReels",
      "patchCatalogPlatformPolicy",
      "pushDshCaptainLocation",
      "putStoreImage",
      "rejectDshControlPanelFinancePayoutRequest",
      "rejectDshPartnerInvite",
      "resolveDshControlPanelFinanceReconciliationCase",
      "reviewReel",
      "submitReel",
      "updateDshPartnerStoreCourierSettings",
      "updateFieldProductProposal",
      "updatePartnerProductProposal",
      "uploadWorkforceMedia",
      "getDshControlPanelFinanceRefund",
      "listDshControlPanelFinanceLedgerEntries",
      "listDshControlPanelFinanceCodRecords",
      "listDshControlPanelFinanceCommissions",
      "listDshCaptainFinanceCodRecords",
      "listDshCatalogApprovals",
      "createDshCatalogApproval",
      "getDshCatalogApproval",
      "transitionDshCatalogApproval",
      "listDshPartnerCatalogApprovals",
      "createDshFieldVisit",
      "listDshFieldVisits",
      "completeDshFieldVisit",
      "upsertDshReadinessCheck",
      "listDshVisitChecks",
      "createDshReadinessEscalation",
      "listDshOperatorEscalations",
      "updateDshOperatorEscalation",
      "getDshPartnerOnboardingStatus",
      "getDshFieldWorkQueue",
      "createDshSupportTicket",
      "listDshMyTickets",
      "getDshSupportTicket",
      "addDshTicketMessage",
      "listDshTicketMessages",
      "listDshOperatorTickets",
      "updateDshOperatorTicket",
      "createDshIncident",
      "listDshIncidents",
      "updateDshIncident",
      "getDshPlatformKpis",
      "getDshOrderAnalytics",
      "getDshDeliveryAnalytics",
      "getDshSupportAnalytics",
      "getDshStoreAnalytics",
      "getDshPartnerPerformance",
      "reportWltPaymentSessionEvent",
      "listDshNotifications",
      "markDshNotificationRead",
      "markAllDshNotificationsRead",
      "updateDshNotificationPreferences",
      "listDshPlatformNotificationConfig",
      "upsertDshPlatformNotificationConfig",
      "listDshCampaigns",
      "createDshCampaign",
      "getDshCampaign",
      "updateDshCampaign",
      "archiveDshCampaign",
      "listDshMarketingTickers",
      "createDshMarketingTicker",
      "updateDshMarketingTicker",
      "deleteDshMarketingTicker",
      "listDshPartnerOffers",
      "updateDshPartnerOffer",
      "archiveDshPartnerOffer",
      "listDshPartnerSelfOffers",
      "submitDshPartnerSelfOffer",
      "listDshZones",
      "createDshZone",
      "updateDshZone",
      "getDshSlaRules",
      "upsertDshSlaRules",
      "getDshCapacityConfig",
      "upsertDshCapacityConfig",
      "getDshZoneServiceability",
      "getDshStoreOnboardingFeePolicy",
      "upsertDshStoreOnboardingFeePolicy",
      "getDshStoreOnboardingFeeReference",
      "listDshAdminRoles",
      "createDshAdminRole",
      "listDshAdminStaff",
      "assignDshStaffRole",
      "listDshPartners",
      "createDshPartner",
      "getDshPartner",
      "transitionDshPartner",
      "getDshPartnerReadiness",
      "listDshPartnerDocuments",
      "addDshPartnerDocument",
      "reviewDshPartnerDocument",
      "listDshPartnerStores",
      "linkDshPartnerStore",
      "listDshPartnerAuditEvents",
      "listDshPartnerFieldVisits",
      "getDshPartnerActivationStatus",
      "getDshPartnerSelfReadiness",
      "listFieldPartnerDrafts",
      "createFieldPartnerDraft",
      "getFieldPartnerDraft",
      "updateFieldPartnerDraft",
      "getFieldPartnerReadiness",
      "getFieldPartnerStore",
      "updateFieldPartnerStore",
      "listFieldPartnerDocuments",
      "uploadFieldPartnerDocument",
      "uploadFieldMedia",
      "getMedia",
      "createFieldPartnerVisit",
      "listFieldPartnerFieldVisits",
      "submitFieldPartnerDraft",
      "listDshPartnerActivations",
      "activateDshPartner",
      "blockDshPartner",
      "listDshCaptainCredentials",
      "upsertDshCaptainCredential",
      "listDshAdminAudit",
      "listCatalogDomains",
      "createCatalogDomain",
      "updateCatalogDomain",
      "listCatalogNodes",
      "createCatalogNode",
      "updateCatalogNode",
      "listMasterProductsOperator",
      "createMasterProduct",
      "updateMasterProduct",
      "listProductProposals",
      "decideProductProposal",
      "transitionProductProposal",
      "listCatalogPlatformPolicies",
      "updateCatalogPlatformPolicy",
      "getCatalogSeedStatus",
      "listCatalogAssets",
      "createAssetUploadIntent",
      "updateCatalogAsset",
      "reviewCatalogAsset",
      "linkCatalogAsset",
      "unlinkCatalogAsset",
      "listCatalogAssetLinks",
      "putDomainImage",
      "putNodeImage",
      "putMasterProductImage",
      "putProductProposalImage",
      "getOperatorStoreAssortment",
      "upsertOperatorStoreAssortment",
      "getPartnerCatalogTaxonomy",
      "listPartnerMasterProducts",
      "getPartnerStoreAssortment",
      "upsertPartnerStoreAssortment",
      "createPartnerProductProposal",
      "getFieldCatalogTaxonomy",
      "listFieldMasterProducts",
      "fieldUpsertStoreAssortment",
      "fieldGetStoreAssortment",
      "createFieldProductProposal",
      "getDshFieldMeWallet",
      "getDshFieldMeCommissions",
      "getDshFieldMePayoutRequests",
      "submitDshFieldMePayoutRequest",
      "getDshFieldMeLedgerEntries",
    ],
    backendRuntimeReady: false,
    generatedClientReady: false,
    databaseReady: false,
    screensReady: false,
    technicalRuntimeReady: false,
    realExperienceReady: false,
    platformControlRuntimeState: "FIX_REQUIRED",
    platformControlReason: "core/platform-control is not implemented yet; /dsh/platform must not claim sovereign runtime readiness.",
    sharedOwnershipEnforced: true,
    controllersInShared: [
      "useStoreAdminController",
      "useStoreDiscoveryController",
      "useStoreRoleContextController",
      "useHomeDiscoveryController",
      "useHomeDiscoveryAdminController",
      "usePartnerCatalogController",
      "usePublishedCatalogController",
      "useCatalogApprovalController",
      "useCatalogAuditController",
      "useCartController",
      "useServiceabilityController",
      "useOperatorCartsController",
      "useCheckoutController",
      "useOperatorCheckoutController",
      "useClientOrdersController",
      "usePartnerOrdersController",
      "useOperatorOrdersController",
      "useCaptainDispatchController",
      "useOperatorDispatchController",
      "useClientTrackingController",
      "useOperatorAnalyticsDashboardController",
      "usePartnerPerformanceController",
      // Partner Onboarding & Store Publication Journey
      "usePartnerOnboardingController",
      "usePartnerAdminController",
      "usePartnerSelfController",
      // Notifications & Actor Communication Journey
      "useNotificationsController",
      "usePlatformNotificationConfigController",
      // Finance WLT Link Controllers
      "useFinanceController",
      "useFinanceVisibilityController",
      "useWltCodController",
      "useWltLedgerController",
      "useWltRefundController",
      "useWltSettlementController",
    ],
    primarySurfaces: [
      "app-client",
      "control-panel",
      "app-partner",
      "app-field",
      "app-captain",
    ],
    requiredStoreRoleSurfaces: ["app-partner", "app-field", "app-captain"],
    incompleteExperienceSurfaces: [
      "app-client checkout",
      "app-partner intake",
      "app-captain pickup-delivery",
      "app-field onboarding-visits",
      "control-panel operations-support",
    ],
    crossSurfaceDependencyMap:
      "services/dsh/frontend/shared/operations/geo-heatmap.helpers.ts",
  },
  nextOperationalJourney: {
    id: "notifications",
    name: "Notifications & Actor Communication",
    closureState: "NEEDS_RUNTIME_EVIDENCE",
  },
  boundaries: {
    ownsOperationalCommerceTruth: true,
    ownsFinancialTruth: false,
    financialOwner: "wlt",
  },
} as const;

export type DshServiceManifest = typeof dshServiceManifest;
