import { DSH_CAPABILITY_MAP } from "./capability-map";
import { DSH_RUNTIME_MAP } from "./runtime-map";
import { DSH_SURFACE_MAP } from "./surface-map";

export const dshServiceManifest = {
  service: "dsh",
  realService: true,
  activatesService: true,
  runtimeState: "RUNTIME_VERIFIED",
  closureState: "RUNTIME_VERIFIED",
  activationScope: "stores-home-discovery-catalog-cart-checkout-wlt-handoff-orders-dispatch-field-readiness-support-analytics",
  contract: "contracts/dsh.openapi.yaml",
  contractState: "CONTRACT_ACTIVE",
  capabilities: DSH_CAPABILITY_MAP,
  surfaces: DSH_SURFACE_MAP,
  runtime: DSH_RUNTIME_MAP,
  currentTruth: {
    contractOperations: [
      // Store Discovery Journey
      "getDshHealth",
      "getDshReadiness",
      "listDshStores",
      "getDshStore",
      // Home Discovery Journey
      "getDshHomeDiscovery",
      "listOperatorHomeDiscoveryContent",
      "createOperatorHomeDiscoveryContent",
      "updateOperatorHomeDiscoveryContent",
      "deleteOperatorHomeDiscoveryContent",
      "getPublishedDshCatalog",
      "getPartnerDshCatalog",
      "createPartnerCatalogCategory",
      "updatePartnerCatalogCategory",
      "deletePartnerCatalogCategory",
      "createPartnerCatalogProduct",
      "updatePartnerCatalogProduct",
      "deletePartnerCatalogProduct",
      "createPartnerCatalogMediaUploadIntent",
      "completePartnerCatalogMedia",
      "deletePartnerCatalogMedia",
      "submitPartnerCatalog",
      "listOperatorCatalogSubmissions",
      "decideOperatorCatalogSubmission",
      "listOperatorCatalogAudit",
      // Cart & Serviceability Journey
      "getDshClientCart",
      "upsertDshCartItem",
      "removeDshCartItem",
      "clearDshCart",
      "checkDshCartServiceability",
      "listOperatorCarts",
      // Checkout & WLT Handoff Journey
      "createDshCheckoutIntent",
      "getDshCheckoutIntent",
      "cancelDshCheckoutIntent",
      "listOperatorCheckoutIntents",
      // Orders Journey
      "createDshOrder",
      "listDshClientOrders",
      "getDshClientOrder",
      "listDshPartnerOrders",
      "acceptDshOrder",
      "rejectDshOrder",
      "markDshOrderPreparing",
      "markDshOrderReadyForPickup",
      "listDshOperatorOrders",
      // Dispatch Journey
      "listDshDispatchAssignments",
      "createDshAssignment",
      "listDshCaptainAssignments",
      "acceptDshAssignment",
      "declineDshAssignment",
      "updateDshDeliveryStatus",
      "submitDshPoD",
      "getDshClientOrderTracking",
      // Field readiness Journey
      "createDshFieldVisit",
      "listDshFieldVisits",
      "completeDshFieldVisit",
      "upsertDshReadinessCheck",
      "listDshVisitChecks",
      "createDshReadinessEscalation",
      "listDshOperatorEscalations",
      "updateDshOperatorEscalation",
      "getDshPartnerOnboardingStatus",
      // Support Journey
      "createDshSupportTicket",
      "listDshMyTickets",
      "getDshSupportTicket",
      "addDshTicketMessage",
      "listDshTicketMessages",
      "listDshOperatorTickets",
      "updateDshOperatorTicket",
      "createDshIncident",
      "listDshIncidents",
      "updateDshIncident",
      // Analytics & Reporting Journey
      "getDshPlatformKpis",
      "getDshOrderAnalytics",
      "getDshDeliveryAnalytics",
      "getDshSupportAnalytics",
      "getDshStoreAnalytics",
      "getDshPartnerPerformance",
      // Partner Onboarding & Store Publication Journey
      "listDshPartners",
      "createDshPartner",
      "getDshPartner",
      "transitionDshPartner",
      "getDshPartnerReadiness",
      "listDshPartnerDocuments",
      "addDshPartnerDocument",
      "reviewDshPartnerDocument",
      "listDshPartnerStores",
      "linkDshPartnerStore",
      "listDshPartnerAuditEvents",
      "listDshPartnerFieldVisits",
      "getDshPartnerActivationStatus",
      "getDshPartnerSelfReadiness",
      "createFieldPartnerDraft",
      "getFieldPartnerDraft",
      "updateFieldPartnerDraft",
      "uploadFieldPartnerDocument",
      "createFieldPartnerVisit",
      "submitFieldPartnerDraft",
    ],
    backendRuntimeReady: true,
    generatedClientReady: true,
    databaseReady: true,
    screensReady: true,
    technicalRuntimeReady: true,
    realExperienceReady: true,
    sharedOwnershipEnforced: true,
    controllersInShared: [
      "useStoreAdminController",
      "useStoreDiscoveryController",
      "useStoreRoleContextController",
      "useHomeDiscoveryController",
      "useHomeDiscoveryAdminController",
      "usePartnerCatalogController",
      "usePublishedCatalogController",
      "useCatalogApprovalController",
      "useCatalogAuditController",
      "useCartController",
      "useServiceabilityController",
      "useOperatorCartsController",
      "useCheckoutController",
      "useOperatorCheckoutController",
      "useClientOrdersController",
      "usePartnerOrdersController",
      "useOperatorOrdersController",
      "useCaptainDispatchController",
      "useOperatorDispatchController",
      "useClientTrackingController",
      "useOperatorAnalyticsDashboardController",
      "usePartnerPerformanceController",
      // Partner Onboarding & Store Publication Journey
      "usePartnerOnboardingController",
      "usePartnerAdminController",
      "usePartnerSelfController",
    ],
    primarySurfaces: [
      "app-client",
      "control-panel",
      "app-partner",
      "app-field",
      "app-captain",
    ],
    requiredStoreRoleSurfaces: ["app-partner", "app-field", "app-captain"],
    incompleteExperienceSurfaces: [],
    crossSurfaceDependencyMap:
      "services/dsh/frontend/shared/runtime/dsh-cross-surface-closure-map.ts",
  },
  nextOperationalJourney: {
    id: "notifications",
    name: "Notifications & Actor Communication",
    closureState: "NEEDS_CONTRACT_EVIDENCE",
  },
  boundaries: {
    ownsOperationalCommerceTruth: true,
    ownsFinancialTruth: false,
    financialOwner: "wlt",
  },
} as const;

export type DshServiceManifest = typeof dshServiceManifest;
