import { DSH_CAPABILITY_MAP } from "./capability-map";
import { DSH_CAPABILITY_MAP_EXTENSIONS } from "./capability-map.extensions";
import { DSH_RUNTIME_MAP } from "./runtime-map";
import { DSH_SURFACE_MAP } from "./surface-map";

export const dshServiceManifest = {
  service: "dsh",
  realService: true,
  activatesService: true,
  runtimeState: "PARTIALLY_BOUND",
  closureState: "FIX_REQUIRED",
  activationScope: "stores-home-discovery-catalog-cart-checkout-wlt-handoff-orders-dispatch-field-readiness-support-analytics-notifications-finance-special-requests-pickup-partner-delivery",
  contract: "contracts/dsh.openapi.yaml",
  contracts: [
    "contracts/dsh.openapi.yaml",
    "contracts/dsh.catalog.openapi.yaml",
    "contracts/dsh.marketing-commercial.openapi.yaml",
    "contracts/dsh.partner-fleet.openapi.yaml",
  ],
  contractFragments: {
    centralCatalog: "contracts/dsh.catalog.openapi.yaml",
    marketingCommercial: "contracts/dsh.marketing-commercial.openapi.yaml",
    partnerFleet: "contracts/dsh.partner-fleet.openapi.yaml",
  },
  contractState: "CONTRACT_ACTIVE",
  capabilityIds: [
    "dsh.system.readiness",
    "dsh.store.discovery",
    "dsh.client.home-discovery",
    "dsh.client.catalog",
    "dsh.client.cart",
    "dsh.client.checkout",
    "dsh.client.orders",
    "dsh.client.dispatch",
    "dsh.field.readiness",
    "dsh.field.finance",
    "dsh.support.hub",
    "dsh.operator.analytics",
    "dsh.notifications",
    "dsh.marketing",
    "dsh.policies",
    "dsh.admin",
    "dsh.partner.activation",
  ],
  capabilities: [...DSH_CAPABILITY_MAP, ...DSH_CAPABILITY_MAP_EXTENSIONS],
  surfaces: DSH_SURFACE_MAP,
  runtime: DSH_RUNTIME_MAP,
  currentTruth: {
    contractOperations: [
      "getDshHealth",
      "getDshReadiness",
      "listDshStores",
      "getDshHomeDiscovery",
      "listOperatorHomeDiscoveryContent",
      "createOperatorHomeDiscoveryContent",
      "updateOperatorHomeDiscoveryContent",
      "deleteOperatorHomeDiscoveryContent",
      "getDshStore",
      "getDshStoreContext",
      "listOperatorDshStores",
      "getOperatorDshStore",
      "updatePartnerStoreSettings",
      "submitFieldStoreVerification",
      "reportCaptainPickupReadiness",
      "governDshStore",
      "listDshStoreAudit",
      "getPublishedDshCatalog",
      "getDshClientCart",
      "clearDshClientCart",
      "upsertDshCartItem",
      "removeDshCartItem",
      "checkDshCartServiceability",
      "listOperatorCarts",
      "createDshCheckoutIntent",
      "getDshCheckoutIntent",
      "cancelDshCheckoutIntent",
      "listOperatorCheckoutIntents",
      "createDshOrder",
      "listDshClientOrders",
      "getDshClientOrder",
      "listDshPartnerOrders",
      "acceptDshOrder",
      "rejectDshOrder",
      "markDshOrderPreparing",
      "markDshOrderReadyForPickup",
      "listDshOperatorOrders",
      "cancelDshOperatorOrder",
      "listDshDispatchAssignments",
      "createDshAssignment",
      "listDshCaptainAssignments",
      "acceptDshAssignment",
      "declineDshAssignment",
      "updateDshDeliveryStatus",
      "submitDshPoD",
      "getDshClientOrderTracking",
      "listDshControlPanelFinanceSettlements",
      "getDshControlPanelFinanceSettlementSummary",
      "listDshControlPanelFinanceRefunds",
      "completeAssetUpload",
      "deleteCatalogAsset",
      "acceptDshPartnerInvite",
      "approveDshControlPanelFinancePayoutRequest",
      "assignDshControlPanelFinanceReconciliationCase",
      "executeDshPartnerStoreTeamMemberAction",
      "getDshControlPanelFinanceFinancialSummary",
      "getDshControlPanelFinanceReconciliationCase",
      "getDshPartnerFinanceSettlementSummary",
      "getDshPartnerStoreCourierSettings",
      "getPartnerStoreSettings",
      "getPublicCatalogMedia",
      "getStoreDiagnostics",
      "inviteDshPartnerStoreTeamMember",
      "listDshControlPanelFinancePayoutRequests",
      "listDshControlPanelFinanceReconciliationCases",
      "listDshPartnerFinanceSettlements",
      "listDshPartnerInvites",
      "listDshPartnerScopes",
      "listDshPartnerStoreCoverageZones",
      "listDshPartnerStoreTeam",
      "listPublicReels",
      "listReels",
      "patchCatalogPlatformPolicy",
      "pushDshCaptainLocation",
      "putStoreImage",
      "rejectDshControlPanelFinancePayoutRequest",
      "rejectDshPartnerInvite",
      "resolveDshControlPanelFinanceReconciliationCase",
      "reviewReel",
      "submitReel",
      "updateDshPartnerStoreCourierSettings",
      "updateFieldProductProposal",
      "updatePartnerProductProposal",
      "uploadWorkforceMedia",
      "getDshControlPanelFinanceRefund",
      "listDshControlPanelFinanceLedgerEntries",
      "listDshControlPanelFinanceCodRecords",
      "listDshControlPanelFinanceCommissions",
      "listDshCaptainFinanceCodRecords",
      "listDshCatalogApprovals",
      "createDshCatalogApproval",
      "getDshCatalogApproval",
      "transitionDshCatalogApproval",
      "listDshPartnerCatalogApprovals",
      "createDshFieldVisit",
      "listDshFieldVisits",
      "completeDshFieldVisit",
      "upsertDshReadinessCheck",
      "listDshVisitChecks",
      "createDshReadinessEscalation",
      "listDshOperatorEscalations",
      "updateDshOperatorEscalation",
      "getDshPartnerOnboardingStatus",
      "getDshFieldWorkQueue",
      "createDshSupportTicket",
      "listDshMyTickets",
      "getDshSupportTicket",
      "addDshTicketMessage",
      "listDshTicketMessages",
      "listDshOperatorTickets",
      "updateDshOperatorTicket",
      "createDshIncident",
      "listDshIncidents",
      "updateDshIncident",
      "getDshPlatformKpis",
      "getDshOrderAnalytics",
      "getDshDeliveryAnalytics",
      "getDshSupportAnalytics",
      "getDshStoreAnalytics",
      "getDshPartnerPerformance",
      "reportWltPaymentSessionEvent",
      "listDshNotifications",
      "markDshNotificationRead",
      "markAllDshNotificationsRead",
      "updateDshNotificationPreferences",
      "listDshPlatformNotificationConfig",
      "upsertDshPlatformNotificationConfig",
      "listDshCampaigns",
      "createDshCampaign",
      "getDshCampaign",
      "updateDshCampaign",
      "archiveDshCampaign",
      "listDshMarketingTickers",
      "createDshMarketingTicker",
      "updateDshMarketingTicker",
      "deleteDshMarketingTicker",
      "listDshPartnerOffers",
      "updateDshPartnerOffer",
      "archiveDshPartnerOffer",
      "listDshPartnerSelfOffers",
      "submitDshPartnerSelfOffer",
      "listDshZones",
      "createDshZone",
      "updateDshZone",
      "getDshSlaRules",
      "upsertDshSlaRules",
      "getDshCapacityConfig",
      "upsertDshCapacityConfig",
      "getDshZoneServiceability",
      "getDshStoreOnboardingFeePolicy",
      "upsertDshStoreOnboardingFeePolicy",
      "getDshStoreOnboardingFeeReference",
      "listDshAdminRoles",
      "createDshAdminRole",
      "listDshAdminStaff",
      "assignDshStaffRole",
      "listDshPartners",
      "createDshPartner",
      "getDshPartner",
      "transitionDshPartner",
      "getDshPartnerReadiness",
      "listDshPartnerDocuments",
      "addDshPartnerDocument",
      "reviewDshPartnerDocument",
      "listDshPartnerStores",
      "linkDshPartnerStore",
      "listDshPartnerAuditEvents",
      "listDshPartnerFieldVisits",
      "getDshPartnerActivationStatus",
      "getDshPartnerSelfReadiness",
      "listFieldPartnerDrafts",
      "createFieldPartnerDraft",
      "getFieldPartnerDraft",
      "updateFieldPartnerDraft",
      "getFieldPartnerReadiness",
      "getFieldPartnerStore",
      "updateFieldPartnerStore",
      "listFieldPartnerDocuments",
      "uploadFieldPartnerDocument",
      "uploadFieldMedia",
      "getMedia",
      "createFieldPartnerVisit",
      "listFieldPartnerFieldVisits",
      "submitFieldPartnerDraft",
      "listDshPartnerActivations",
      "activateDshPartner",
      "blockDshPartner",
      "listDshCaptainCredentials",
      "upsertDshCaptainCredential",
      "listDshAdminAudit",
      "listCatalogDomains",
      "createCatalogDomain",
      "updateCatalogDomain",
      "listCatalogNodes",
      "createCatalogNode",
      "updateCatalogNode",
      "listMasterProductsOperator",
      "createMasterProduct",
      "updateMasterProduct",
      "listProductProposals",
      "decideProductProposal",
      "transitionProductProposal",
      "listCatalogPlatformPolicies",
      "updateCatalogPlatformPolicy",
      "getCatalogSeedStatus",
      "listCatalogAssets",
      "createAssetUploadIntent",
      "updateCatalogAsset",
      "reviewCatalogAsset",
      "linkCatalogAsset",
      "unlinkCatalogAsset",
      "listCatalogAssetLinks",
      "putDomainImage",
      "putNodeImage",
      "putMasterProductImage",
      "putProductProposalImage",
      "getOperatorStoreAssortment",
      "upsertOperatorStoreAssortment",
      "getPartnerCatalogTaxonomy",
      "listPartnerMasterProducts",
      "getPartnerStoreAssortment",
      "upsertPartnerStoreAssortment",
      "createPartnerProductProposal",
      "getFieldCatalogTaxonomy",
      "listFieldMasterProducts",
      "fieldUpsertStoreAssortment",
      "fieldGetStoreAssortment",
      "createFieldProductProposal",
      "getDshFieldMeWallet",
      "getDshFieldMeCommissions",
      "getDshFieldMePayoutRequests",
      "submitDshFieldMePayoutRequest",
      "getDshFieldMeLedgerEntries",
      "DELETEDshFieldFinancePayoutDestinationsDestinationId",
      "GETDshCaptainFinanceCommissions",
      "GETDshCaptainFinancePayouts",
      "GETDshFieldFinanceCommissions",
      "GETDshFieldFinancePayoutDestinations",
      "GETDshFieldFinancePayouts",
      "GETDshFieldFinanceWallet",
      "PATCHDshFieldFinancePayoutDestinationsDestinationId",
      "POSTDshCaptainFinanceCodRecordsRecordIdCollect",
      "POSTDshCaptainFinanceCodRecordsRecordIdRemit",
      "POSTDshCaptainFinancePayouts",
      "POSTDshFieldFinancePayoutDestinations",
      "POSTDshFieldFinancePayouts",
      "approveDshSpecialRequestQuote",
      "arriveDshPartnerDeliveryTask",
      "assignDshPartnerDeliveryTask",
      "assignDshSpecialRequestDispatch",
      "cancelDshClientSpecialRequest",
      "completeDshControlPanelFinancePayoutRequest",
      "createDshClientSpecialRequest",
      "createDshGovernedSettlementFromDeliveredOrders",
      "departDshPartnerDeliveryTask",
      "extendDshPickupWindow",
      "failDshControlPanelFinancePayoutRequest",
      "getDshClientSpecialRequest",
      "getDshOperatorPartnerDelivery",
      "getDshOperatorPickup",
      "getDshOperatorSpecialRequest",
      "listDshClientSpecialRequests",
      "listDshOperatorPartnerDeliveries",
      "listDshOperatorPickups",
      "listDshOperatorSpecialRequests",
      "markDshPartnerDeliveryPickedUp",
      "markDshPickupCustomerArrived",
      "markDshPickupNoShow",
      "markDshPickupReady",
      "notifyDshPickupCustomer",
      "processDshControlPanelFinancePayoutRequest",
      "raiseDshPartnerDeliveryException",
      "submitDshPartnerDeliveryProof",
      "updateDshOperatorSpecialRequest",
      "upsertDshSettlementPolicy",
      "verifyDshPickupSession",
    ],
    catalogContract: {
      path: "contracts/dsh.catalog.openapi.yaml",
      state: "CONTRACT_ACTIVE",
      optimisticConcurrency: "REQUIRED",
      conflictStatus: 409,
      clientGeneration: "ENABLED",
    },
    backendRuntimeReady: true,
    generatedClientReady: true,
    databaseReady: true,
    screensReady: false,
    technicalRuntimeReady: false,
    realExperienceReady: false,
    platformControlRuntimeState: "VERIFICATION_REQUIRED",
    platformControlReason: "core/platform-control P3 governed changes, live health, progressive rollout, audit, and rollback are implemented; same-commit runtime and independent release evidence remain required.",
  },
} as const;
