// Design primitives live in @bthwani/ui-kit/web. Re-exported here for backwards compatibility.
export {
  CpButton,
  CpSelect,
  CpSearchInput,
  CpTextInput,
  CpTable,
  CpTableHeaderCell,
  CpTableCell,
  CpKpiCard,
  CpKpiStrip,
  CpPageHeader,
  CpFilterBar,
  CpStatePanel,
  CpRetryButton,
  CpEmptyTableMessage,
  CpSelectableTableRow,
  CpInlineCode,
  CpMutedInline,
  CpDetailPanel,
  CpDetailMessage,
  CpDetailError,
  CpDescriptionList,
  CpDescriptionRow,
  CpExternalLink,
} from "@bthwani/ui-kit/web";

export type {
  CpButtonProps,
  CpSelectOption,
  CpSelectProps,
  CpSearchInputProps,
  CpTextInputProps,
  CpTableProps,
  CpTableHeaderCellProps,
  CpTableCellProps,
  CpKpiCardProps,
} from "@bthwani/ui-kit/web";
