package http

import (
	"database/sql"
	"net/http"

	"dsh-api/internal/auth"
	"dsh-api/internal/cache"
	"dsh-api/internal/health"
	"dsh-api/internal/homediscovery"
	"dsh-api/internal/media"
	"dsh-api/internal/platformclient"
	"dsh-api/internal/store"
	"dsh-api/internal/wlt"
)

func NewRouter(db *sql.DB, identityClient *auth.Client, wltClient *wlt.Client, platformClient *platformclient.Client, mediaProvider *media.Provider, respCache *cache.Client) *http.ServeMux {
	mux := http.NewServeMux()

	mux.HandleFunc("GET /dsh/health", health.HandleHealth)
	mux.HandleFunc("GET /dsh/readiness", health.HandleReadiness(db, mediaProvider, identityClient))
	mux.HandleFunc("GET /dsh/stores", store.HandleListStores(db))
	mux.HandleFunc("GET /dsh/stores/{storeId}", store.HandleGetStore(db))
	mux.HandleFunc("GET /dsh/storefront/{storeId}", handlePublicStorefront(db))
	mux.HandleFunc("GET /dsh/stores/{storeId}/catalog", handlePublicCatalog(db))
	mux.HandleFunc("GET /dsh/public/media/{assetId}/{variant}", handlePublicMedia(db, mediaProvider))
	mux.HandleFunc("GET /dsh/public/reels", handlePublicReels(db))
	mux.HandleFunc("GET /dsh/home-discovery", homediscovery.HandleHomeDiscovery(db, respCache))
	mux.HandleFunc("POST /dsh/home-discovery/events", homediscovery.HandleHomeContentEvent(db))
	protected := newProtectedStoreServer(db, identityClient, wltClient, platformClient, mediaProvider)
	onboardingCollaborationRoutes(mux, protected)
	mux.HandleFunc("POST /dsh/field/media/uploads", protected.withFieldActor(protected.handleFieldMediaUpload))
	mux.HandleFunc("GET /dsh/media", protected.handleMediaDownload)
	mux.HandleFunc("GET /dsh/store-context", protected.handleStoreContext)
	mux.HandleFunc("GET /dsh/operator/stores", protected.withPermission("control-panel", PartnersPermissionRead, protected.handleOperatorStores))
	mux.HandleFunc("POST /dsh/operator/stores", protected.withPermission("control-panel", PartnersPermissionManage, protected.handleOperatorCreateStore))
	mux.HandleFunc("GET /dsh/operator/stores/{storeId}", protected.withPermission("control-panel", PartnersPermissionRead, protected.handleOperatorStoreDetail))
	mux.HandleFunc("GET /dsh/operator/diagnostics/stores/{storeId}", protected.withPermission("control-panel", PartnersPermissionRead, protected.handleGovernedOperatorStoreDiagnostics))
	mux.HandleFunc("GET /dsh/operator/marketing/stores/{storeId}/publication", protected.withPermission("control-panel", MarketingPermissionRead, protected.handleGetMarketingStorePublication))
	mux.HandleFunc("POST /dsh/operator/marketing/stores/{storeId}/publication", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleMarketingStorePublication))
	mux.HandleFunc("GET /dsh/operator/stores/{storeId}/delivery-pricing", protected.withPermission("control-panel", "operations.read", protected.handleOperatorListDeliveryPricing))
	mux.HandleFunc("PUT /dsh/operator/stores/{storeId}/delivery-pricing/{fulfillmentMode}", protected.withPermission("control-panel", "operations.manage", protected.handleOperatorUpsertDeliveryPricing))
	mux.HandleFunc("POST /dsh/partner/stores", protected.handlePartnerCreateStore)
	mux.HandleFunc("GET /dsh/partner/stores/{storeId}/settings", protected.handleGetPartnerSettings)
	mux.HandleFunc("PATCH /dsh/partner/stores/{storeId}/settings", protected.handlePartnerSettings)
	mux.HandleFunc("GET /dsh/partner/stores/{storeId}/courier-settings", protected.handlePartnerGetCourierSettings)
	mux.HandleFunc("PUT /dsh/partner/stores/{storeId}/courier-settings", protected.handlePartnerUpdateCourierSettings)
	mux.HandleFunc("GET /dsh/partner/stores/{storeId}/coverage-zones", protected.handlePartnerCoverageZones)
	mux.HandleFunc("GET /dsh/partner/stores/{storeId}/delivery-pricing", protected.handlePartnerListDeliveryPricing)
	mux.HandleFunc("PUT /dsh/partner/stores/{storeId}/delivery-pricing/{fulfillmentMode}", protected.handlePartnerUpsertDeliveryPricing)
	mux.HandleFunc("GET /dsh/partner/stores/{storeId}/commercial-summary", protected.handlePartnerCommercialSummary)
	mux.HandleFunc("POST /dsh/partner/stores/{storeId}/couriers/{memberId}/connection-code", protected.handleIssuePartnerCourierConnectionCode)
	mux.HandleFunc("GET /dsh/partner/stores/{storeId}/courier-connections", protected.handleListPartnerCourierConnections)
	mux.HandleFunc("POST /dsh/partner/stores/{storeId}/courier-connections/{connectionId}/revoke", protected.handleRevokePartnerCourierConnection)
	mux.HandleFunc("GET /dsh/partner/stores/{storeId}/team", protected.handleListPartnerStoreTeam)
	mux.HandleFunc("POST /dsh/partner/stores/{storeId}/team/invites", protected.handleInvitePartnerStoreTeamMember)
	mux.HandleFunc("POST /dsh/partner/stores/{storeId}/team/members/{memberId}/action", protected.handlePartnerStoreTeamMemberAction)

	mux.HandleFunc("GET /dsh/partner/scopes", protected.handlePartnerScopes)
	mux.HandleFunc("POST /dsh/field/stores", protected.withFieldActor(protected.handleFieldCreateStore))
	mux.HandleFunc("POST /dsh/field/stores/{storeId}/verifications", protected.withFieldActor(protected.handleFieldVerification))
	mux.HandleFunc("POST /dsh/captain/stores/{storeId}/pickup-readiness", protected.handleCaptainReadiness)
	mux.HandleFunc("POST /dsh/captain/partner-fleet/connect", protected.handleCaptainConnectPartnerFleet)
	mux.HandleFunc("GET /dsh/captain/partner-fleet/memberships", protected.handleCaptainPartnerFleetMemberships)
	mux.HandleFunc("POST /dsh/operator/stores/{storeId}/governance", protected.withPermission("control-panel", PartnersPermissionManage, protected.handleOperatorGovernance))
	mux.HandleFunc("GET /dsh/operator/stores/{storeId}/audit", protected.withPermission("control-panel", PartnersPermissionRead, protected.handleStoreAudit))
	mux.HandleFunc("GET /dsh/operator/home-discovery/{kind}", protected.withPermission("control-panel", MarketingPermissionRead, protected.handleHomeDiscoveryAdminList))
	mux.HandleFunc("POST /dsh/operator/home-discovery/{kind}", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleHomeDiscoveryAdminCreate))
	mux.HandleFunc("PATCH /dsh/operator/home-discovery/{kind}/{itemId}", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleHomeDiscoveryAdminUpdate))
	mux.HandleFunc("DELETE /dsh/operator/home-discovery/{kind}/{itemId}", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleHomeDiscoveryAdminDelete))
	mux.HandleFunc("GET /dsh/operator/home-discovery/{kind}/{itemId}/targeting", protected.withPermission("control-panel", MarketingPermissionRead, protected.handleHomeDiscoveryAdminTargetingGet))
	mux.HandleFunc("PUT /dsh/operator/home-discovery/{kind}/{itemId}/targeting", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleHomeDiscoveryAdminTargetingPut))
	mux.HandleFunc("GET /dsh/operator/platform/service-areas", protected.withPermission("control-panel", DshServiceZonesPermissionRead, protected.handleOperatorListServiceAreas))
	mux.HandleFunc("PUT /dsh/operator/platform/service-areas/{serviceAreaCode}", protected.withPermission("control-panel", DshServiceZonesPermissionManage, protected.handleOperatorUpsertServiceArea))

	mux.HandleFunc("GET /dsh/client/me/profile", protected.handleGetClientProfile)
	mux.HandleFunc("PATCH /dsh/client/me/profile/preferences", protected.handleUpsertClientProfilePreferences)
	mux.HandleFunc("PATCH /dsh/client/me/profile/consents", protected.handleUpsertClientProfileConsents)
	mux.HandleFunc("GET /dsh/administration/customers/{actorId}/profile", protected.handleAdminGetClientProfile)
	mux.HandleFunc("GET /dsh/client/cart", protected.handleGetCart)
	mux.HandleFunc("POST /dsh/client/cart/items", protected.handleUpsertCartItem)
	mux.HandleFunc("DELETE /dsh/client/cart/items/{itemId}", protected.handleRemoveCartItem)
	mux.HandleFunc("DELETE /dsh/client/cart", protected.handleClearCart)
	mux.HandleFunc("GET /dsh/client/cart/fulfillment-modes", protected.handleGetFulfillmentModes)
	mux.HandleFunc("POST /dsh/client/cart/serviceability", protected.handleCartServiceability)
	mux.HandleFunc("GET /dsh/client/addresses", protected.handleListClientAddresses)
	mux.HandleFunc("POST /dsh/client/addresses", protected.handleCreateClientAddress)
	mux.HandleFunc("PATCH /dsh/client/addresses/{addressId}", protected.handleUpdateClientAddress)
	mux.HandleFunc("DELETE /dsh/client/addresses/{addressId}", protected.handleDeleteClientAddress)
	mux.HandleFunc("POST /dsh/client/addresses/{addressId}/default", protected.handleSetClientDefaultAddress)
	mux.HandleFunc("POST /dsh/client/maps/search", protected.handleClientMapSearch)
	mux.HandleFunc("POST /dsh/client/maps/reverse", protected.handleClientMapReverse)
	mux.HandleFunc("GET /dsh/operator/carts", protected.withPermission("control-panel", OperationsPermissionRead, protected.handleOperatorCarts))
	mux.HandleFunc("GET /dsh/internal/operations/carts/{cartId}/sync-diagnostics", protected.withPermission("control-panel", OperationsPermissionRead, protected.handleOperatorCartSyncDiagnostics))

	mux.HandleFunc("POST /dsh/client/checkout-intents", protected.handleCreateCheckoutIntent)
	mux.HandleFunc("GET /dsh/client/checkout-intents/{intentId}", protected.handleGetCheckoutIntent)
	mux.HandleFunc("POST /dsh/client/checkout-intents/{intentId}/cancel", protected.handleCancelCheckoutIntent)
	mux.HandleFunc("POST /dsh/client/checkout-intents/{intentId}/validate", protected.handleValidateCheckoutIntent)
	mux.HandleFunc("POST /dsh/client/checkout-intents/{intentId}/refresh", protected.handleRefreshCheckoutIntent)
	mux.HandleFunc("GET /dsh/operator/checkout-intents", protected.withPermission("control-panel", OperationsPermissionRead, protected.handleOperatorCheckoutIntents))
	mux.HandleFunc("POST /dsh/operator/checkout-intents/{intentId}/reconcile", protected.withPermission("control-panel", OperationsPermissionManage, protected.handleReconcileCheckoutIntent))
	mux.HandleFunc("POST /dsh/internal/wlt/payment-session-events", protected.handleWltPaymentSessionEvent)

	mux.HandleFunc("POST /dsh/client/orders", protected.handleCreateOrderTruth)
	mux.HandleFunc("GET /dsh/client/orders", protected.handleListClientOrderTruth)
	mux.HandleFunc("GET /dsh/client/orders/{orderId}", protected.handleGetClientOrderTruth)
	mux.HandleFunc("GET /dsh/partner/orders", protected.handleListPartnerOrderTruth)
	mux.HandleFunc("GET /dsh/partner/order-workboard", protected.handlePartnerOrderWorkboard)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/decision", protected.handlePartnerOrderDecision)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/preparing", protected.handleMarkPreparing)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/ready", protected.handleMarkReadyForPickup)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/captain-handoff/confirm", protected.handleConfirmPartnerStoreCaptainHandoff)
	mux.HandleFunc("GET /dsh/operator/orders", protected.withPermission("control-panel", OperationsPermissionRead, protected.handleListOperatorOrderTruth))
	mux.HandleFunc("GET /dsh/operator/orders/{orderId}", protected.withPermission("control-panel", OperationsPermissionRead, protected.handleGetOperatorOrderTruth))
	mux.HandleFunc("POST /dsh/operator/orders/{orderId}/cancel", protected.withPermission("control-panel", OperationsPermissionManage, protected.handleOperatorCancelOrder))
	mux.HandleFunc("POST /dsh/client/orders/{orderId}/return", protected.handleClientReturnOrder)
	mux.HandleFunc("GET /dsh/client/orders/{orderId}/return", protected.handleClientGetReturnOrder)
	mux.HandleFunc("POST /dsh/operator/orders/{orderId}/return", protected.withPermission("control-panel", OperationsPermissionManage, protected.handleOperatorReturnOrderGoverned))

	mux.HandleFunc("GET /dsh/captain/me/readiness", protected.handleGetCaptainSelfReadiness)
	mux.HandleFunc("GET /dsh/operator/dispatch/captains/{captainId}/readiness", protected.withPermission("control-panel", OperationsPermissionRead, protected.handleGetCaptainOperatorReadiness))
	mux.HandleFunc("POST /dsh/operator/dispatch/assignments", protected.withPermission("control-panel", OperationsPermissionManage, protected.handleCreateGovernedDispatchAssignment))
	mux.HandleFunc("GET /dsh/operator/dispatch/assignments", protected.withPermission("control-panel", OperationsPermissionRead, protected.handleListGovernedOperatorDispatchAssignments))
	mux.HandleFunc("GET /dsh/operator/dispatch/tracking-alerts", protected.withPermission("control-panel", OperationsPermissionRead, protected.handleListDispatchTrackingAlerts))
	mux.HandleFunc("GET /dsh/captain/dispatch/assignments", protected.handleListGovernedCaptainDispatchAssignments)
	mux.HandleFunc("GET /dsh/captain/dispatch/availability", protected.handleGetCaptainAvailability)
	mux.HandleFunc("PATCH /dsh/captain/dispatch/availability", protected.handleSetCaptainAvailability)
	mux.HandleFunc("POST /dsh/captain/dispatch/assignments/{assignmentId}/accept", protected.handleAcceptGovernedDispatchAssignment)
	mux.HandleFunc("POST /dsh/captain/dispatch/assignments/{assignmentId}/decline", protected.handleDeclineGovernedDispatchAssignment)
	mux.HandleFunc("PUT /dsh/operator/dispatch/captains/{captainId}/profile", protected.withPermission("control-panel", OperationsPermissionManage, protected.handleUpsertCaptainDispatchProfile))
	mux.HandleFunc("GET /dsh/operator/dispatch/candidates", protected.withPermission("control-panel", OperationsPermissionRead, protected.handleListCaptainDispatchCandidates))
	mux.HandleFunc("POST /dsh/operator/dispatch/assignments/{assignmentId}/reassign", protected.withPermission("control-panel", OperationsPermissionManage, protected.handleReassignGovernedDispatchAssignment))
	mux.HandleFunc("POST /dsh/operator/dispatch/assignments/{assignmentId}/cancel", protected.withPermission("control-panel", OperationsPermissionManage, protected.handleCancelGovernedDispatchAssignment))
	mux.HandleFunc("POST /dsh/operator/dispatch/assignments/expire", protected.withPermission("control-panel", OperationsPermissionManage, protected.handleExpireGovernedDispatchAssignments))
	mux.HandleFunc("GET /dsh/operator/dispatch/decisions", protected.withPermission("control-panel", OperationsPermissionRead, protected.handleListDispatchDecisions))
	mux.HandleFunc("POST /dsh/captain/dispatch/assignments/{assignmentId}/status", protected.handleGovernedUpdateDeliveryStatus)
	mux.HandleFunc("POST /dsh/captain/dispatch/assignments/{assignmentId}/pod", protected.handleSubmitDispatchPoDWithMedia)
	mux.HandleFunc("POST /dsh/captain/dispatch/assignments/{assignmentId}/location", protected.handlePushDispatchLocationGoverned)
	mux.HandleFunc("POST /dsh/captain/dispatch/assignments/{assignmentId}/exceptions", protected.handleReportDeliveryException)
	mux.HandleFunc("GET /dsh/captain/dispatch/assignments/{assignmentId}/exceptions", protected.handleGetCaptainDeliveryException)
	mux.HandleFunc("POST /dsh/captain/dispatch/assignments/{assignmentId}/contact-proxy", protected.handleCaptainContactProxy)
	mux.HandleFunc("POST /dsh/captain/dispatch/assignments/{assignmentId}/return-to-store/arrive", protected.handleArriveReturnToStore)
	mux.HandleFunc("GET /dsh/operator/delivery-exceptions", protected.withPermission("control-panel", OperationsPermissionRead, protected.handleListOperatorDeliveryExceptions))
	mux.HandleFunc("POST /dsh/operator/delivery-exceptions/{exceptionId}/acknowledge", protected.withPermission("control-panel", OperationsPermissionManage, protected.handleAcknowledgeDeliveryException))
	mux.HandleFunc("POST /dsh/operator/delivery-exceptions/{exceptionId}/resolve", protected.withPermission("control-panel", OperationsPermissionManage, protected.handleResolveDeliveryException))
	mux.HandleFunc("GET /dsh/client/orders/{orderId}/tracking", protected.handleGetClientLiveTracking)
	mux.HandleFunc("GET /dsh/partner/orders/{orderId}/dispatch-tracking", protected.handleGetPartnerDispatchTrackingReference)

	mux.HandleFunc("POST /dsh/client/special-requests", protected.handleCreateSpecialRequest)
	mux.HandleFunc("GET /dsh/client/special-requests", protected.handleListClientSpecialRequests)
	mux.HandleFunc("GET /dsh/client/special-requests/{requestId}", protected.handleGetClientSpecialRequest)
	mux.HandleFunc("GET /dsh/client/special-requests/{requestId}/information-exchange", protected.handleGetClientSpecialRequestInformation)
	mux.HandleFunc("POST /dsh/client/special-requests/{requestId}/information-response", protected.handleRespondSpecialRequestInformation)
	mux.HandleFunc("GET /dsh/client/special-requests/{requestId}/execution", protected.handleGetClientSpecialRequestExecution)
	mux.HandleFunc("POST /dsh/client/special-requests/{requestId}/cancel", protected.handleCancelClientSpecialRequest)
	mux.HandleFunc("POST /dsh/client/special-requests/{requestId}/approve-quote", protected.handleApproveSpecialRequestQuote)
	mux.HandleFunc("GET /dsh/operator/special-requests", protected.withPermission("control-panel", OperationsSpecialRequestsPermissionRead, protected.handleListOperatorSpecialRequests))
	mux.HandleFunc("GET /dsh/operator/special-requests/{requestId}", protected.withPermission("control-panel", OperationsSpecialRequestsPermissionRead, protected.handleGetOperatorSpecialRequest))
	mux.HandleFunc("GET /dsh/operator/special-requests/{requestId}/information-exchange", protected.withPermission("control-panel", OperationsSpecialRequestsPermissionRead, protected.handleGetOperatorSpecialRequestInformation))
	mux.HandleFunc("POST /dsh/operator/special-requests/{requestId}/information-request", protected.withPermission("control-panel", OperationsSpecialRequestsPermissionTransition, protected.handleRequestSpecialRequestInformation))
	mux.HandleFunc("GET /dsh/operator/special-requests/{requestId}/execution", protected.withPermission("control-panel", OperationsSpecialRequestsPermissionRead, protected.handleGetOperatorSpecialRequestExecution))
	mux.HandleFunc("PATCH /dsh/operator/special-requests/{requestId}", protected.withPermission("control-panel", OperationsSpecialRequestsPermissionTransition, protected.handleUpdateOperatorSpecialRequest))
	mux.HandleFunc("POST /dsh/operator/special-requests/{requestId}/dispatch", protected.withPermission("control-panel", OperationsSpecialRequestsPermissionDispatch, protected.handleAssignSpecialRequestDispatch))

	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/partner-delivery/assign", protected.handleAssignPartnerDelivery)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/partner-delivery/pickup", protected.handlePartnerDeliveryPickup)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/partner-delivery/depart", protected.handlePartnerDeliveryDepart)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/partner-delivery/arrive", protected.handlePartnerDeliveryArrive)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/partner-delivery/proof", protected.handlePartnerDeliveryProofWithMedia)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/partner-delivery/exception", protected.withPermission("control-panel", IncidentPermissionOverride, protected.handlePartnerDeliveryException))
	mux.HandleFunc("GET /dsh/partner/orders/{orderId}/return-to-store", protected.handleGetPartnerReturnToStore)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/return-to-store/accept", protected.handleAcceptPartnerReturnToStore)
	mux.HandleFunc("GET /dsh/operator/partner-deliveries", protected.withPermission("control-panel", PartnerDeliveryPermissionRead, protected.handleListOperatorPartnerDeliveries))
	mux.HandleFunc("GET /dsh/operator/partner-deliveries/{taskId}", protected.withPermission("control-panel", PartnerDeliveryPermissionRead, protected.handleGetOperatorPartnerDelivery))
	mux.HandleFunc("GET /dsh/operator/partner-deliveries/order/{orderId}", protected.withPermission("control-panel", PartnerDeliveryPermissionRead, protected.handleGetOperatorPartnerDeliveryByOrder))
	mux.HandleFunc("GET /dsh/client/orders/{orderId}/pickup", protected.handleGetClientPickupSession)
	mux.HandleFunc("GET /dsh/client/orders/{orderId}/partner-delivery", protected.handleGetClientPartnerDeliveryTask)
	mux.HandleFunc("GET /dsh/partner/orders/{orderId}/pickup", protected.handleGetPartnerPickupState)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/pickup/mark-ready", protected.handlePickupMarkReady)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/pickup/notify", protected.handlePickupNotify)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/pickup/customer-arrived", protected.handlePickupCustomerArrived)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/pickup/verify", protected.handlePickupVerify)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/pickup/no-show", protected.handlePickupNoShow)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/pickup/extend-window", protected.handlePartnerExtendPickupWindow)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/pickup/reschedule", protected.handlePartnerReschedulePickupWindow)
	mux.HandleFunc("GET /dsh/operator/pickups", protected.withPermission("control-panel", PickupPermissionRead, protected.handleListOperatorPickups))
	mux.HandleFunc("GET /dsh/operator/pickups/{orderId}", protected.withPermission("control-panel", PickupPermissionRead, protected.handleGetOperatorPickup))
	mux.HandleFunc("POST /dsh/operator/pickups/{orderId}/extend-window", protected.withPermission("control-panel", IncidentPermissionOverride, protected.handleExtendPickupWindow))

	mux.HandleFunc("POST /dsh/operator/operational-incidents", protected.withPermission("control-panel", IncidentPermissionOverride, protected.handleReportOperationalIncident))
	mux.HandleFunc("GET /dsh/operator/operational-incidents", protected.withPermission("control-panel", PartnerDeliveryPermissionRead, protected.handleListOperatorIncidents))
	mux.HandleFunc("GET /dsh/operator/operational-incidents/{incidentId}", protected.withPermission("control-panel", PartnerDeliveryPermissionRead, protected.handleGetOperatorIncident))
	mux.HandleFunc("POST /dsh/operator/partner-delivery/sla-alerts/refresh", protected.withPermission("control-panel", PartnerDeliveryPermissionManage, protected.handleRefreshDeliverySLAAlerts))
	mux.HandleFunc("GET /dsh/operator/partner-delivery/sla-alerts", protected.withPermission("control-panel", PartnerDeliveryPermissionRead, protected.handleListDeliverySLAAlerts))
	mux.HandleFunc("POST /dsh/operator/partner-delivery/sla-alerts/{alertId}/acknowledge", protected.withPermission("control-panel", PartnerDeliveryPermissionManage, protected.handleAcknowledgeDeliverySLAAlert))
	mux.HandleFunc("POST /dsh/operator/pickups/sla-alerts/refresh", protected.withPermission("control-panel", PickupPermissionManage, protected.handleRefreshPickupSLAAlerts))
	mux.HandleFunc("GET /dsh/operator/pickups/sla-alerts", protected.withPermission("control-panel", PickupPermissionRead, protected.handleListPickupSLAAlerts))
	mux.HandleFunc("POST /dsh/operator/pickups/sla-alerts/{alertId}/acknowledge", protected.withPermission("control-panel", PickupPermissionManage, protected.handleAcknowledgePickupSLAAlert))

	mux.HandleFunc("GET /dsh/control-panel/finance/payment-sessions/{paymentSessionId}/timeline", protected.withPermission("control-panel", FinancePermissionRead, protected.handleFinancePaymentSessionTimeline))
	mux.HandleFunc("GET /dsh/control-panel/finance/settlements", protected.withPermission("control-panel", FinancePermissionRead, protected.handleFinanceSettlements))
	mux.HandleFunc("GET /dsh/control-panel/finance/settlements/summary", protected.withPermission("control-panel", FinancePermissionRead, protected.handleFinanceSettlementSummary))
	mux.HandleFunc("GET /dsh/partner/me/finance/settlements", protected.handlePartnerFinanceSettlements)
	mux.HandleFunc("GET /dsh/partner/me/finance/settlements/summary", protected.handlePartnerFinanceSettlementSummary)
	mux.HandleFunc("GET /dsh/control-panel/finance/refunds", protected.withPermission("control-panel", FinancePermissionRead, protected.handleFinanceRefunds))
	mux.HandleFunc("GET /dsh/control-panel/finance/refunds/{refundId}", protected.withPermission("control-panel", FinancePermissionRead, protected.handleFinanceRefundDetail))
	mux.HandleFunc("GET /dsh/control-panel/finance/ledger/entries", protected.withPermission("control-panel", FinancePermissionRead, protected.handleFinanceLedgerEntries))
	mux.HandleFunc("GET /dsh/control-panel/finance/financial-summary", protected.withPermission("control-panel", FinancePermissionRead, protected.handleFinanceFinancialSummary))
	mux.HandleFunc("GET /dsh/control-panel/finance/commissions", protected.withPermission("control-panel", FinancePermissionRead, protected.handleFinanceCommissions))
	mux.HandleFunc("GET /dsh/control-panel/finance/payout-requests", protected.withPermission("control-panel", FinancePermissionRead, protected.handleFinancePayoutRequests))
	mux.HandleFunc("GET /dsh/control-panel/finance/reconciliation-cases", protected.withPermission("control-panel", FinancePermissionRead, protected.handleFinanceReconciliationCases))
	mux.HandleFunc("GET /dsh/control-panel/finance/reconciliation-cases/{caseId}", protected.withPermission("control-panel", FinancePermissionRead, protected.handleFinanceReconciliationCaseDetail))
	mux.HandleFunc("GET /dsh/control-panel/finance/references/payment-status", protected.withPermission("control-panel", FinancePermissionRead, protected.handleFinanceReferencesPaymentStatus))
	mux.HandleFunc("GET /dsh/control-panel/finance/references/settlement-status", protected.withPermission("control-panel", FinancePermissionRead, protected.handleFinanceReferencesSettlementStatus))
	mux.HandleFunc("GET /dsh/control-panel/finance/references/refund-status", protected.withPermission("control-panel", FinancePermissionRead, protected.handleFinanceReferencesRefundStatus))
	mux.HandleFunc("GET /dsh/control-panel/finance/references/field-commission", protected.withPermission("control-panel", FinancePermissionRead, protected.handleFinanceReferencesFieldCommission))

	// Representative self-service finance routes are composed once, from
	// registerUnifiedCatalogRoutes below. A second call here registered the
	// same patterns twice and made net/http panic while building the router,
	// which took down every DSH HTTP test rather than one route.

	mux.HandleFunc("POST /dsh/support/tickets", protected.handleCreateActorSupportTicket)
	mux.HandleFunc("GET /dsh/support/tickets", protected.handleListActorSupportTickets)
	mux.HandleFunc("GET /dsh/support/tickets/{ticketId}", protected.handleGetActorSupportTicket)
	mux.HandleFunc("GET /dsh/support/tickets/{ticketId}/messages", protected.handleListActorSupportMessages)
	mux.HandleFunc("POST /dsh/support/tickets/{ticketId}/messages", protected.handleAddActorSupportMessage)
	mux.HandleFunc("GET /dsh/operator/support/tickets", protected.withPermission("control-panel", SupportPermissionRead, protected.handleListGovernedOperatorSupportTickets))
	mux.HandleFunc("GET /dsh/operator/support/tickets/{ticketId}", protected.withPermission("control-panel", SupportPermissionRead, protected.handleGetGovernedOperatorSupportTicket))
	mux.HandleFunc("PATCH /dsh/operator/support/tickets/{ticketId}", protected.withPermission("control-panel", SupportPermissionManage, protected.handleUpdateGovernedOperatorSupportTicket))
	mux.HandleFunc("GET /dsh/operator/support/tickets/{ticketId}/messages", protected.withPermission("control-panel", SupportPermissionRead, protected.handleListGovernedOperatorSupportMessages))
	mux.HandleFunc("POST /dsh/operator/support/tickets/{ticketId}/messages", protected.withPermission("control-panel", SupportPermissionManage, protected.handleAddGovernedOperatorSupportMessage))
	mux.HandleFunc("GET /dsh/operator/support/tickets/{ticketId}/events", protected.withPermission("control-panel", SupportPermissionRead, protected.handleListGovernedOperatorSupportEvents))
	mux.HandleFunc("POST /dsh/operator/support/tickets/{ticketId}/claim", protected.withPermission("control-panel", SupportPermissionManage, protected.handleClaimOperatorSupportTicket))
	mux.HandleFunc("POST /dsh/operator/support/tickets/{ticketId}/escalate", protected.withPermission("control-panel", SupportPermissionManage, protected.handleEscalateOperatorSupportTicket))
	mux.HandleFunc("GET /dsh/operator/support/tickets/{ticketId}/export", protected.withPermission("control-panel", SupportPermissionRead, protected.handleExportOperatorSupportTicket))
	mux.HandleFunc("GET /dsh/operator/support/canned-responses", protected.withPermission("control-panel", SupportPermissionRead, protected.handleListCannedResponses))
	mux.HandleFunc("GET /dsh/operator/analytics/operations", protected.withPermission("control-panel", AnalyticsPermissionRead, protected.handleGetOperationsAnalytics))
	mux.HandleFunc("GET /dsh/operator/analytics/support", protected.withPermission("control-panel", AnalyticsPermissionRead, protected.handleGetSupportAnalytics))

	mux.HandleFunc("GET /dsh/operator/marketing/campaigns", protected.withPermission("control-panel", MarketingPermissionRead, protected.handleListCampaigns))
	mux.HandleFunc("POST /dsh/operator/marketing/campaigns", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleCreateCampaign))
	mux.HandleFunc("GET /dsh/operator/marketing/campaigns/{campaignId}", protected.withPermission("control-panel", MarketingPermissionRead, protected.handleGetCampaign))
	mux.HandleFunc("PATCH /dsh/operator/marketing/campaigns/{campaignId}", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleUpdateCampaign))
	mux.HandleFunc("DELETE /dsh/operator/marketing/campaigns/{campaignId}", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleArchiveCampaign))
	mux.HandleFunc("GET /dsh/operator/marketing/tickers", protected.withPermission("control-panel", MarketingPermissionRead, protected.handleListMarketingTickers))
	mux.HandleFunc("POST /dsh/operator/marketing/tickers", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleCreateMarketingTicker))
	mux.HandleFunc("PATCH /dsh/operator/marketing/tickers/{tickerId}", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleUpdateMarketingTicker))
	mux.HandleFunc("DELETE /dsh/operator/marketing/tickers/{tickerId}", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleDeleteMarketingTicker))
	mux.HandleFunc("GET /dsh/operator/marketing/partner-offers", protected.withPermission("control-panel", MarketingPermissionRead, protected.handleListPartnerOffers))
	mux.HandleFunc("PATCH /dsh/operator/marketing/partner-offers/{offerId}", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleUpdatePartnerOffer))
	mux.HandleFunc("DELETE /dsh/operator/marketing/partner-offers/{offerId}", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleArchivePartnerOffer))
	mux.HandleFunc("GET /dsh/operator/marketing/coupons", protected.withPermission("control-panel", MarketingPermissionRead, protected.handleListCoupons))
	mux.HandleFunc("POST /dsh/operator/marketing/coupons", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleCreateCoupon))
	mux.HandleFunc("PATCH /dsh/operator/marketing/coupons/{couponId}", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleUpdateCoupon))
	mux.HandleFunc("GET /dsh/partner/marketing/offers", protected.handleListPartnerSelfOffers)
	mux.HandleFunc("POST /dsh/partner/marketing/offers", protected.handleSubmitPartnerOffer)
	mux.HandleFunc("GET /dsh/operator/marketing/loyalty-tiers", protected.withPermission("control-panel", MarketingPermissionRead, protected.handleListMarketingLoyaltyTiers))
	mux.HandleFunc("POST /dsh/operator/marketing/loyalty-tiers", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleCreateMarketingLoyaltyTier))
	mux.HandleFunc("PATCH /dsh/operator/marketing/loyalty-tiers/{tierId}", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleUpdateMarketingLoyaltyTier))
	mux.HandleFunc("GET /dsh/operator/marketing/loyalty-earning-policies", protected.withPermission("control-panel", MarketingPermissionRead, protected.handleListLoyaltyEarningPolicies))
	mux.HandleFunc("POST /dsh/operator/marketing/loyalty-earning-policies", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleCreateLoyaltyEarningPolicy))
	mux.HandleFunc("PATCH /dsh/operator/marketing/loyalty-earning-policies/{policyId}", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleUpdateLoyaltyEarningPolicy))
	mux.HandleFunc("GET /dsh/operator/marketing/subscription-plans", protected.withPermission("control-panel", MarketingPermissionRead, protected.handleListMarketingSubscriptionPlans))
	mux.HandleFunc("POST /dsh/operator/marketing/subscription-plans", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleCreateMarketingSubscriptionPlan))
	mux.HandleFunc("PATCH /dsh/operator/marketing/subscription-plans/{planId}", protected.withPermission("control-panel", MarketingPermissionManage, protected.handleUpdateMarketingSubscriptionPlan))
	mux.HandleFunc("POST /dsh/client/marketing/subscriptions/purchase", protected.handleCreateSubscriptionPurchase)
	mux.HandleFunc("GET /dsh/client/marketing/subscriptions/purchases/{purchaseId}", protected.handleGetSubscriptionPurchase)
	mux.HandleFunc("POST /dsh/client/marketing/subscriptions/purchases/{purchaseId}/activate", protected.handleActivateSubscriptionPurchase)
	mux.HandleFunc("POST /dsh/client/marketing/subscriptions/instances/{subscriptionId}/renew", protected.handleRenewSubscriptionPurchase)
	mux.HandleFunc("POST /dsh/client/marketing/subscriptions/instances/{subscriptionId}/cancel", protected.handleCancelSubscriptionPurchase)
	mux.HandleFunc("GET /dsh/client/benefits", protected.handleClientBenefits)

	mux.HandleFunc("GET /dsh/field/catalog/master-products", protected.withFieldActor(protected.handleListMasterProducts))
	mux.HandleFunc("GET /dsh/partner/catalog/master-products", protected.handleListMasterProducts)

	registerUnifiedCatalogRoutes(mux, protected)

	mux.HandleFunc("GET /dsh/operator/platform/store-onboarding-fee", protected.handleGetStoreOnboardingFeePolicy)
	mux.HandleFunc("PUT /dsh/operator/platform/store-onboarding-fee", protected.handleUpsertStoreOnboardingFeePolicy)
	mux.HandleFunc("GET /dsh/platform/store-onboarding-fee", protected.handleGetStoreOnboardingFeeReference)

	mux.HandleFunc("GET /dsh/operator/admin/roles", protected.handleListRoles)
	mux.HandleFunc("GET /dsh/operator/admin/staff", protected.handleListStaff)
	mux.HandleFunc("POST /dsh/operator/admin/staff/{staffId}/roles", protected.handleCreateRoleAssignment)
	mux.HandleFunc("GET /dsh/partner/invites", protected.handleNotImplemented)
	mux.HandleFunc("POST /dsh/partner/invites/{inviteId}/accept", protected.handleNotImplemented)
	mux.HandleFunc("POST /dsh/partner/invites/{inviteId}/reject", protected.handleNotImplemented)
	mux.HandleFunc("POST /dsh/operator/admin/roles/requests", protected.handleCreateRoleRequest)
	mux.HandleFunc("GET /dsh/operator/admin/role-requests", protected.handleListRoleRequests)
	mux.HandleFunc("POST /dsh/operator/admin/role-requests/{requestId}/review", protected.handleReviewRoleRequest)
	mux.HandleFunc("POST /dsh/operator/admin/role-requests/{requestId}/replacements", protected.handleReplaceFailedRoleRequest)
	mux.HandleFunc("GET /dsh/operator/admin/approvals", protected.handleListRoleAssignmentApprovals)
	mux.HandleFunc("POST /dsh/operator/admin/approvals/{approvalId}/review", protected.handleReviewRoleAssignmentApproval)
	mux.HandleFunc("POST /dsh/operator/admin/approvals/{approvalId}/replacements", protected.handleReplaceFailedRoleAssignmentApproval)
	mux.HandleFunc("POST /dsh/operator/admin/approvals/{approvalId}/rollback-requests", protected.handleCreateRollbackRequest)
	mux.HandleFunc("GET /dsh/operator/admin/rollback-requests", protected.handleListRollbackRequests)
	mux.HandleFunc("POST /dsh/operator/admin/rollback-requests/{requestId}/review", protected.handleReviewRollbackRequest)
	mux.HandleFunc("POST /dsh/operator/admin/rollback-requests/{requestId}/replacements", protected.handleReplaceFailedRollbackRequest)
	mux.HandleFunc("GET /dsh/operator/admin/diagnostics", protected.handleGetDiagnostics)

	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/accept", protected.handlePartnerAcceptOrder)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/reject", protected.handlePartnerRejectOrder)
	return mux
}

func (s *protectedStoreServer) handleNotImplemented(w http.ResponseWriter, r *http.Request) {
	store.SendError(w, http.StatusNotImplemented, "NOT_IMPLEMENTED", "not implemented")
}
