package http

import (
	"database/sql"
	"net/http"

	"dsh-api/internal/auth"
	"dsh-api/internal/health"
	"dsh-api/internal/homediscovery"
	"dsh-api/internal/media"
	"dsh-api/internal/store"
	"dsh-api/internal/wlt"
)

func NewRouter(db *sql.DB, identityClient *auth.Client, wltClient *wlt.Client, mediaProvider *media.Provider) *http.ServeMux {
	mux := http.NewServeMux()

	mux.HandleFunc("GET /dsh/health", health.HandleHealth)
	mux.HandleFunc("GET /dsh/readiness", health.HandleReadiness(db, mediaProvider))
	mux.HandleFunc("GET /dsh/stores", store.HandleListStores(db))
	mux.HandleFunc("GET /dsh/stores/{storeId}", store.HandleGetStore(db))
	mux.HandleFunc("GET /dsh/stores/{storeId}/catalog", handlePublicCatalog(db))
	mux.HandleFunc("GET /dsh/public/media/{assetId}/{variant}", handlePublicMedia(db, mediaProvider))
	mux.HandleFunc("GET /dsh/public/reels", handlePublicReels(db))
	mux.HandleFunc("GET /dsh/home-discovery", homediscovery.HandleHomeDiscovery(db))
	mux.HandleFunc("POST /dsh/home-discovery/events", homediscovery.HandleHomeContentEvent(db))
	protected := newProtectedStoreServer(db, identityClient, wltClient, mediaProvider)
	mux.HandleFunc("POST /dsh/field/media/uploads", protected.handleFieldMediaUpload)
	mux.HandleFunc("GET /dsh/media", protected.handleMediaDownload)
	mux.HandleFunc("GET /dsh/store-context", protected.handleStoreContext)
	mux.HandleFunc("GET /dsh/operator/stores", protected.handleOperatorStores)
	mux.HandleFunc("GET /dsh/operator/stores/{storeId}", protected.handleOperatorStoreDetail)
	mux.HandleFunc("GET /dsh/operator/diagnostics/stores/{storeId}", protected.handleGovernedOperatorStoreDiagnostics)
	mux.HandleFunc("GET /dsh/operator/stores/{storeId}/delivery-pricing", protected.handleOperatorListDeliveryPricing)
	mux.HandleFunc("PUT /dsh/operator/stores/{storeId}/delivery-pricing/{fulfillmentMode}", protected.handleOperatorUpsertDeliveryPricing)
	mux.HandleFunc("GET /dsh/partner/stores/{storeId}/settings", protected.handleGetPartnerSettings)
	mux.HandleFunc("PATCH /dsh/partner/stores/{storeId}/settings", protected.handlePartnerSettings)
	mux.HandleFunc("GET /dsh/partner/stores/{storeId}/team", protected.handlePartnerStoreTeam)
	mux.HandleFunc("POST /dsh/partner/stores/{storeId}/team/invites", protected.handlePartnerInviteTeamMember)
	mux.HandleFunc("POST /dsh/partner/stores/{storeId}/team/members/{memberId}/action", protected.handlePartnerTeamMemberActionAudited)
	mux.HandleFunc("GET /dsh/partner/stores/{storeId}/courier-settings", protected.handlePartnerGetCourierSettings)
	mux.HandleFunc("PUT /dsh/partner/stores/{storeId}/courier-settings", protected.handlePartnerUpdateCourierSettings)
	mux.HandleFunc("GET /dsh/partner/stores/{storeId}/coverage-zones", protected.handlePartnerCoverageZones)
	mux.HandleFunc("GET /dsh/partner/stores/{storeId}/delivery-pricing", protected.handlePartnerListDeliveryPricing)
	mux.HandleFunc("PUT /dsh/partner/stores/{storeId}/delivery-pricing/{fulfillmentMode}", protected.handlePartnerUpsertDeliveryPricing)
	mux.HandleFunc("POST /dsh/partner/stores/{storeId}/couriers/{memberId}/connection-code", protected.handleIssuePartnerCourierConnectionCode)
	mux.HandleFunc("GET /dsh/partner/stores/{storeId}/courier-connections", protected.handleListPartnerCourierConnections)
	mux.HandleFunc("POST /dsh/partner/stores/{storeId}/courier-connections/{connectionId}/revoke", protected.handleRevokePartnerCourierConnection)
	mux.HandleFunc("GET /dsh/partner/invites", protected.handlePartnerListInvites)
	mux.HandleFunc("POST /dsh/partner/invites/{inviteId}/accept", protected.handlePartnerAcceptInvite)
	mux.HandleFunc("POST /dsh/partner/invites/{inviteId}/reject", protected.handlePartnerRejectInvite)
	mux.HandleFunc("GET /dsh/partner/scopes", protected.handlePartnerScopes)
	mux.HandleFunc("POST /dsh/field/stores/{storeId}/verifications", protected.handleFieldVerification)
	mux.HandleFunc("POST /dsh/captain/stores/{storeId}/pickup-readiness", protected.handleCaptainReadiness)
	mux.HandleFunc("POST /dsh/captain/partner-fleet/connect", protected.handleCaptainConnectPartnerFleet)
	mux.HandleFunc("GET /dsh/captain/partner-fleet/memberships", protected.handleCaptainPartnerFleetMemberships)
	mux.HandleFunc("POST /dsh/operator/stores/{storeId}/governance", protected.handleOperatorGovernance)
	mux.HandleFunc("GET /dsh/operator/stores/{storeId}/audit", protected.handleStoreAudit)
	mux.HandleFunc("GET /dsh/operator/home-discovery/{kind}", protected.handleHomeDiscoveryAdminList)
	mux.HandleFunc("POST /dsh/operator/home-discovery/{kind}", protected.handleHomeDiscoveryAdminCreate)
	mux.HandleFunc("PATCH /dsh/operator/home-discovery/{kind}/{itemId}", protected.handleHomeDiscoveryAdminUpdate)
	mux.HandleFunc("DELETE /dsh/operator/home-discovery/{kind}/{itemId}", protected.handleHomeDiscoveryAdminDelete)
	mux.HandleFunc("GET /dsh/operator/platform/service-areas", protected.handleOperatorListServiceAreas)
	mux.HandleFunc("PUT /dsh/operator/platform/service-areas/{serviceAreaCode}", protected.handleOperatorUpsertServiceArea)

	// Cart, client address book, governed maps, and serviceability.
	mux.HandleFunc("GET /dsh/client/cart", protected.handleGetCart)
	mux.HandleFunc("POST /dsh/client/cart/items", protected.handleUpsertCartItem)
	mux.HandleFunc("DELETE /dsh/client/cart/items/{itemId}", protected.handleRemoveCartItem)
	mux.HandleFunc("DELETE /dsh/client/cart", protected.handleClearCart)
	mux.HandleFunc("POST /dsh/client/cart/serviceability", protected.handleCartServiceability)
	mux.HandleFunc("GET /dsh/client/addresses", protected.handleListClientAddresses)
	mux.HandleFunc("POST /dsh/client/addresses", protected.handleCreateClientAddress)
	mux.HandleFunc("PATCH /dsh/client/addresses/{addressId}", protected.handleUpdateClientAddress)
	mux.HandleFunc("DELETE /dsh/client/addresses/{addressId}", protected.handleDeleteClientAddress)
	mux.HandleFunc("POST /dsh/client/addresses/{addressId}/default", protected.handleSetClientDefaultAddress)
	mux.HandleFunc("POST /dsh/client/maps/search", protected.handleClientMapSearch)
	mux.HandleFunc("POST /dsh/client/maps/reverse", protected.handleClientMapReverse)
	mux.HandleFunc("GET /dsh/operator/carts", protected.handleOperatorCarts)

	// Checkout Intent & WLT Handoff
	mux.HandleFunc("POST /dsh/client/checkout-intents", protected.handleCreateCheckoutIntent)
	mux.HandleFunc("GET /dsh/client/checkout-intents/{intentId}", protected.handleGetCheckoutIntent)
	mux.HandleFunc("POST /dsh/client/checkout-intents/{intentId}/cancel", protected.handleCancelCheckoutIntent)
	mux.HandleFunc("GET /dsh/operator/checkout-intents", protected.handleOperatorCheckoutIntents)
	mux.HandleFunc("POST /dsh/operator/checkout-intents/{intentId}/reconcile", protected.handleReconcileCheckoutIntent)
	mux.HandleFunc("POST /dsh/internal/wlt/payment-session-events", protected.handleWltPaymentSessionEvent)

	// Order Fulfillment & Partner Acceptance
	mux.HandleFunc("POST /dsh/client/orders", protected.handleCreateOrder)
	mux.HandleFunc("GET /dsh/client/orders", protected.handleListClientOrders)
	mux.HandleFunc("GET /dsh/client/orders/{orderId}", protected.handleGetClientOrder)
	mux.HandleFunc("GET /dsh/partner/orders", protected.handleListPartnerOrders)
	mux.HandleFunc("GET /dsh/partner/order-workboard", protected.handlePartnerOrderWorkboard)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/accept", protected.handleAcceptOrder)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/reject", protected.handleRejectOrder)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/preparing", protected.handleMarkPreparing)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/ready", protected.handleMarkReadyForPickup)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/captain-handoff/confirm", protected.handleConfirmPartnerStoreCaptainHandoff)
	mux.HandleFunc("GET /dsh/operator/orders", protected.handleListOperatorOrders)
	mux.HandleFunc("POST /dsh/operator/orders/{orderId}/cancel", protected.handleOperatorCancelOrder)

	// Dispatch & Captain Delivery Lifecycle
	mux.HandleFunc("POST /dsh/operator/dispatch/assignments", protected.handleCreateDispatchAssignment)
	mux.HandleFunc("GET /dsh/operator/dispatch/assignments", protected.handleListOperatorDispatchAssignments)
	mux.HandleFunc("GET /dsh/captain/dispatch/assignments", protected.handleListCaptainDispatchAssignments)
	mux.HandleFunc("POST /dsh/captain/dispatch/assignments/{assignmentId}/accept", protected.handleAcceptDispatchAssignment)
	mux.HandleFunc("POST /dsh/captain/dispatch/assignments/{assignmentId}/decline", protected.handleDeclineDispatchAssignment)
	mux.HandleFunc("POST /dsh/captain/dispatch/assignments/{assignmentId}/status", protected.handleGovernedUpdateDeliveryStatus)
	mux.HandleFunc("POST /dsh/captain/dispatch/assignments/{assignmentId}/pod", protected.handleSubmitDispatchPoDWithMedia)
	mux.HandleFunc("POST /dsh/captain/dispatch/assignments/{assignmentId}/location", protected.handlePushDispatchLocationGoverned)
	mux.HandleFunc("POST /dsh/captain/dispatch/assignments/{assignmentId}/exceptions", protected.handleReportDeliveryException)
	mux.HandleFunc("GET /dsh/captain/dispatch/assignments/{assignmentId}/exceptions", protected.handleGetCaptainDeliveryException)
	mux.HandleFunc("POST /dsh/captain/dispatch/assignments/{assignmentId}/return-to-store/arrive", protected.handleArriveReturnToStore)
	mux.HandleFunc("GET /dsh/operator/delivery-exceptions", protected.handleListOperatorDeliveryExceptions)
	mux.HandleFunc("POST /dsh/operator/delivery-exceptions/{exceptionId}/acknowledge", protected.handleAcknowledgeDeliveryException)
	mux.HandleFunc("POST /dsh/operator/delivery-exceptions/{exceptionId}/resolve", protected.handleResolveDeliveryException)
	mux.HandleFunc("GET /dsh/client/orders/{orderId}/tracking", protected.handleGetClientTracking)
	mux.HandleFunc("GET /dsh/partner/orders/{orderId}/dispatch-tracking", protected.handleGetPartnerDispatchTracking)

	// Special Requests (Shein, Awnak)
	mux.HandleFunc("POST /dsh/client/special-requests", protected.handleCreateSpecialRequest)
	mux.HandleFunc("GET /dsh/client/special-requests", protected.handleListClientSpecialRequests)
	mux.HandleFunc("GET /dsh/client/special-requests/{requestId}", protected.handleGetClientSpecialRequest)
	mux.HandleFunc("POST /dsh/client/special-requests/{requestId}/cancel", protected.handleCancelClientSpecialRequest)
	mux.HandleFunc("POST /dsh/client/special-requests/{requestId}/approve-quote", protected.handleApproveSpecialRequestQuote)
	mux.HandleFunc("GET /dsh/operator/special-requests", protected.handleListOperatorSpecialRequests)
	mux.HandleFunc("GET /dsh/operator/special-requests/{requestId}", protected.handleGetOperatorSpecialRequest)
	mux.HandleFunc("PATCH /dsh/operator/special-requests/{requestId}", protected.handleUpdateOperatorSpecialRequest)
	mux.HandleFunc("POST /dsh/operator/special-requests/{requestId}/dispatch", protected.handleAssignSpecialRequestDispatch)

	// Partner Delivery & Pickup Operational Closure
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/partner-delivery/assign", protected.handleAssignPartnerDelivery)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/partner-delivery/pickup", protected.handlePartnerDeliveryPickup)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/partner-delivery/depart", protected.handlePartnerDeliveryDepart)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/partner-delivery/arrive", protected.handlePartnerDeliveryArrive)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/partner-delivery/proof", protected.handlePartnerDeliveryProofWithMedia)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/partner-delivery/exception", protected.handlePartnerDeliveryException)
	mux.HandleFunc("GET /dsh/partner/orders/{orderId}/return-to-store", protected.handleGetPartnerReturnToStore)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/return-to-store/accept", protected.handleAcceptPartnerReturnToStore)
	mux.HandleFunc("GET /dsh/operator/partner-deliveries", protected.handleListOperatorPartnerDeliveries)
	mux.HandleFunc("GET /dsh/operator/partner-deliveries/{taskId}", protected.handleGetOperatorPartnerDelivery)
	mux.HandleFunc("GET /dsh/operator/partner-deliveries/order/{orderId}", protected.handleGetOperatorPartnerDeliveryByOrder)
	mux.HandleFunc("GET /dsh/client/orders/{orderId}/pickup", protected.handleGetClientPickupSession)
	mux.HandleFunc("GET /dsh/client/orders/{orderId}/partner-delivery", protected.handleGetClientPartnerDeliveryTask)
	mux.HandleFunc("GET /dsh/partner/orders/{orderId}/pickup", protected.handleGetPartnerPickupState)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/pickup/mark-ready", protected.handlePickupMarkReady)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/pickup/notify", protected.handlePickupNotify)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/pickup/customer-arrived", protected.handlePickupCustomerArrived)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/pickup/verify", protected.handlePickupVerify)
	mux.HandleFunc("POST /dsh/partner/orders/{orderId}/pickup/no-show", protected.handlePickupNoShow)
	mux.HandleFunc("GET /dsh/operator/pickups", protected.handleListOperatorPickups)
	mux.HandleFunc("GET /dsh/operator/pickups/{orderId}", protected.handleGetOperatorPickup)
	mux.HandleFunc("POST /dsh/operator/pickups/{orderId}/extend-window", protected.handleExtendPickupWindow)

	// Governed finance proxy — WLT remains the sole owner of financial truth.
	mux.HandleFunc("GET /dsh/control-panel/finance/settlements", protected.handleFinanceSettlements)
	mux.HandleFunc("GET /dsh/control-panel/finance/settlements/summary", protected.handleFinanceSettlementSummary)
	mux.HandleFunc("POST /dsh/control-panel/finance/settlements/from-delivered-orders", protected.handleCreateFinanceSettlementFromDeliveredOrders)
	mux.HandleFunc("PUT /dsh/control-panel/finance/settlement-policies/{partnerId}", protected.handleUpsertFinanceSettlementPolicy)
	mux.HandleFunc("GET /dsh/partner/me/finance/settlements", protected.handlePartnerFinanceSettlements)
	mux.HandleFunc("GET /dsh/partner/me/finance/settlements/summary", protected.handlePartnerFinanceSettlementSummary)
	mux.HandleFunc("GET /dsh/control-panel/finance/refunds", protected.handleFinanceRefunds)
	mux.HandleFunc("GET /dsh/control-panel/finance/refunds/{refundId}", protected.handleFinanceRefundDetail)
	mux.HandleFunc("GET /dsh/control-panel/finance/ledger/entries", protected.handleFinanceLedgerEntries)
	mux.HandleFunc("GET /dsh/control-panel/finance/financial-summary", protected.handleFinanceFinancialSummary)
	mux.HandleFunc("GET /dsh/control-panel/finance/cod-records", protected.handleFinanceCodRecords)
	mux.HandleFunc("GET /dsh/control-panel/finance/commissions", protected.handleFinanceCommissions)
	mux.HandleFunc("GET /dsh/control-panel/finance/payout-requests", protected.handleFinancePayoutRequests)
	mux.HandleFunc("POST /dsh/control-panel/finance/payout-requests/{payoutId}/approve", protected.handleApproveFinancePayoutRequest)
	mux.HandleFunc("POST /dsh/control-panel/finance/payout-requests/{payoutId}/reject", protected.handleRejectFinancePayoutRequest)
	mux.HandleFunc("POST /dsh/control-panel/finance/payout-requests/{payoutId}/process", protected.handleProcessFinancePayoutRequest)
	mux.HandleFunc("POST /dsh/control-panel/finance/payout-requests/{payoutId}/complete", protected.handleCompleteFinancePayoutRequest)
	mux.HandleFunc("POST /dsh/control-panel/finance/payout-requests/{payoutId}/fail", protected.handleFailFinancePayoutRequest)
	mux.HandleFunc("GET /dsh/control-panel/finance/reconciliation-cases", protected.handleFinanceReconciliationCases)
	mux.HandleFunc("GET /dsh/control-panel/finance/reconciliation-cases/{caseId}", protected.handleFinanceReconciliationCaseDetail)
	mux.HandleFunc("POST /dsh/control-panel/finance/reconciliation-cases/{caseId}/assign", protected.handleAssignFinanceReconciliationCase)
	mux.HandleFunc("POST /dsh/control-panel/finance/reconciliation-cases/{caseId}/resolve", protected.handleResolveFinanceReconciliationCase)
	mux.HandleFunc("GET /dsh/captain/finance/cod-records", protected.handleCaptainFinanceCodRecords)
	mux.HandleFunc("POST /dsh/captain/finance/cod-records/{recordId}/collect", protected.handleCaptainCollectCod)
	mux.HandleFunc("POST /dsh/captain/finance/cod-records/{recordId}/remit", protected.handleCaptainRemitCod)
	mux.HandleFunc("GET /dsh/captain/finance/commissions", protected.handleCaptainFinanceCommissions)
	mux.HandleFunc("GET /dsh/captain/finance/payouts", protected.handleCaptainFinancePayouts)
	mux.HandleFunc("POST /dsh/captain/finance/payouts", protected.handleCaptainCreatePayout)
	mux.HandleFunc("GET /dsh/field/finance/commissions", protected.handleFieldFinanceCommissions)
	mux.HandleFunc("GET /dsh/field/finance/wallet", protected.handleFieldFinanceWallet)
	mux.HandleFunc("GET /dsh/field/finance/payouts", protected.handleFieldFinancePayouts)
	mux.HandleFunc("POST /dsh/field/finance/payouts", protected.handleFieldCreatePayout)
	mux.HandleFunc("GET /dsh/field/finance/payout-destinations", protected.handleFieldListPayoutDestinations)
	mux.HandleFunc("POST /dsh/field/finance/payout-destinations", protected.handleFieldCreatePayoutDestination)
	mux.HandleFunc("PATCH /dsh/field/finance/payout-destinations/{destinationId}", protected.handleFieldUpdatePayoutDestination)
	mux.HandleFunc("DELETE /dsh/field/finance/payout-destinations/{destinationId}", protected.handleFieldDeletePayoutDestination)

	// Primary-contract compatibility routes remain actor-owned and retry-safe.
	mux.HandleFunc("POST /dsh/support/tickets", protected.handleCreateActorSupportTicket)
	mux.HandleFunc("GET /dsh/support/tickets", protected.handleListActorSupportTickets)
	mux.HandleFunc("GET /dsh/support/tickets/{ticketId}", protected.handleGetActorSupportTicket)
	mux.HandleFunc("GET /dsh/support/tickets/{ticketId}/messages", protected.handleListActorSupportMessages)
	mux.HandleFunc("POST /dsh/support/tickets/{ticketId}/messages", protected.handleAddActorSupportMessage)

	// Actor-specific support routes provide stronger role-specific contracts.
	mux.HandleFunc("POST /dsh/client/support/tickets", protected.handleCreateGovernedClientSupportTicket)
	mux.HandleFunc("GET /dsh/client/support/tickets", protected.handleListGovernedClientSupportTickets)
	mux.HandleFunc("GET /dsh/client/support/tickets/{ticketId}", protected.handleGetGovernedClientSupportTicket)
	mux.HandleFunc("GET /dsh/client/support/tickets/{ticketId}/messages", protected.handleListGovernedClientSupportMessages)
	mux.HandleFunc("POST /dsh/client/support/tickets/{ticketId}/messages", protected.handleAddGovernedClientSupportMessage)
	mux.HandleFunc("POST /dsh/partner/support/tickets", protected.handleCreatePartnerSupportTicket)
	mux.HandleFunc("GET /dsh/partner/support/tickets", protected.handleListPartnerSupportTickets)
	mux.HandleFunc("GET /dsh/partner/support/tickets/{ticketId}", protected.handleGetPartnerSupportTicket)
	mux.HandleFunc("GET /dsh/partner/support/tickets/{ticketId}/messages", protected.handleListPartnerSupportMessages)
	mux.HandleFunc("POST /dsh/partner/support/tickets/{ticketId}/messages", protected.handleAddPartnerSupportMessage)
	mux.HandleFunc("GET /dsh/operator/support/tickets", protected.handleListGovernedOperatorSupportTickets)
	mux.HandleFunc("GET /dsh/operator/support/tickets/{ticketId}", protected.handleGetGovernedOperatorSupportTicket)
	mux.HandleFunc("PATCH /dsh/operator/support/tickets/{ticketId}", protected.handleUpdateGovernedOperatorSupportTicket)
	mux.HandleFunc("GET /dsh/operator/support/tickets/{ticketId}/messages", protected.handleListGovernedOperatorSupportMessages)
	mux.HandleFunc("POST /dsh/operator/support/tickets/{ticketId}/messages", protected.handleAddGovernedOperatorSupportMessage)
	mux.HandleFunc("GET /dsh/operator/support/tickets/{ticketId}/events", protected.handleListGovernedOperatorSupportEvents)
	mux.HandleFunc("POST /dsh/operator/incidents", protected.handleCreateIncident)
	mux.HandleFunc("GET /dsh/operator/incidents", protected.handleListIncidents)
	mux.HandleFunc("PATCH /dsh/operator/incidents/{incidentId}", protected.handleUpdateIncident)

	// Operations & Observability
	mux.HandleFunc("GET /dsh/operator/analytics/operations", protected.handleGetOperationsAnalytics)
	mux.HandleFunc("GET /dsh/operator/analytics/support", protected.handleGetSupportAnalytics)

	// Marketing & Campaign Governance
	mux.HandleFunc("GET /dsh/operator/marketing/campaigns", protected.handleListCampaigns)
	mux.HandleFunc("POST /dsh/operator/marketing/campaigns", protected.handleCreateCampaign)
	mux.HandleFunc("GET /dsh/operator/marketing/campaigns/{campaignId}", protected.handleGetCampaign)
	mux.HandleFunc("PATCH /dsh/operator/marketing/campaigns/{campaignId}", protected.handleUpdateCampaign)
	mux.HandleFunc("DELETE /dsh/operator/marketing/campaigns/{campaignId}", protected.handleArchiveCampaign)
	mux.HandleFunc("GET /dsh/operator/marketing/tickers", protected.handleListMarketingTickers)
	mux.HandleFunc("POST /dsh/operator/marketing/tickers", protected.handleCreateMarketingTicker)
	mux.HandleFunc("PATCH /dsh/operator/marketing/tickers/{tickerId}", protected.handleUpdateMarketingTicker)
	mux.HandleFunc("DELETE /dsh/operator/marketing/tickers/{tickerId}", protected.handleDeleteMarketingTicker)
	mux.HandleFunc("GET /dsh/operator/marketing/partner-offers", protected.handleListPartnerOffers)
	mux.HandleFunc("PATCH /dsh/operator/marketing/partner-offers/{offerId}", protected.handleUpdatePartnerOffer)
	mux.HandleFunc("DELETE /dsh/operator/marketing/partner-offers/{offerId}", protected.handleArchivePartnerOffer)
	mux.HandleFunc("GET /dsh/operator/marketing/coupons", protected.handleListCoupons)
	mux.HandleFunc("POST /dsh/operator/marketing/coupons", protected.handleCreateCoupon)
	mux.HandleFunc("PATCH /dsh/operator/marketing/coupons/{couponId}", protected.handleUpdateCoupon)
	mux.HandleFunc("GET /dsh/partner/marketing/offers", protected.handleListPartnerSelfOffers)
	mux.HandleFunc("POST /dsh/partner/marketing/offers", protected.handleSubmitPartnerOffer)
	mux.HandleFunc("GET /dsh/operator/marketing/loyalty-tiers", protected.handleListMarketingLoyaltyTiers)
	mux.HandleFunc("POST /dsh/operator/marketing/loyalty-tiers", protected.handleCreateMarketingLoyaltyTier)
	mux.HandleFunc("PATCH /dsh/operator/marketing/loyalty-tiers/{tierId}", protected.handleUpdateMarketingLoyaltyTier)
	mux.HandleFunc("GET /dsh/operator/marketing/loyalty-earning-policies", protected.handleListLoyaltyEarningPolicies)
	mux.HandleFunc("POST /dsh/operator/marketing/loyalty-earning-policies", protected.handleCreateLoyaltyEarningPolicy)
	mux.HandleFunc("PATCH /dsh/operator/marketing/loyalty-earning-policies/{policyId}", protected.handleUpdateLoyaltyEarningPolicy)
	mux.HandleFunc("GET /dsh/operator/marketing/subscription-plans", protected.handleListMarketingSubscriptionPlans)
	mux.HandleFunc("POST /dsh/operator/marketing/subscription-plans", protected.handleCreateMarketingSubscriptionPlan)
	mux.HandleFunc("PATCH /dsh/operator/marketing/subscription-plans/{planId}", protected.handleUpdateMarketingSubscriptionPlan)
	mux.HandleFunc("POST /dsh/client/marketing/subscriptions/purchase", protected.handleCreateClientSubscriptionPurchase)
	mux.HandleFunc("POST /dsh/client/marketing/subscriptions/{purchaseId}/activate", protected.handleActivateClientSubscription)
	mux.HandleFunc("GET /dsh/client/benefits", protected.handleClientBenefits)

	// Central Catalog compatibility surface.
	mux.HandleFunc("GET /dsh/catalog/domains", protected.handleListCatalogDomains)
	mux.HandleFunc("POST /dsh/catalog/domains", protected.handleCreateCatalogDomain)
	mux.HandleFunc("PATCH /dsh/catalog/domains/{domainId}", protected.handleUpdateCatalogDomainAtomic)
	mux.HandleFunc("GET /dsh/catalog/nodes", protected.handleListCatalogNodes)
	mux.HandleFunc("POST /dsh/catalog/nodes", protected.handleCreateCatalogNode)
	mux.HandleFunc("PATCH /dsh/catalog/nodes/{nodeId}", protected.handleUpdateCatalogNodeAtomic)
	mux.HandleFunc("GET /dsh/catalog/master-products", protected.handleListCatalogMasterProducts)
	mux.HandleFunc("POST /dsh/catalog/master-products", protected.handleCreateCatalogMasterProduct)
	mux.HandleFunc("PATCH /dsh/catalog/master-products/{productId}", protected.handleUpdateCatalogMasterProductAtomic)
	mux.HandleFunc("GET /dsh/catalog/proposals", protected.handleListCatalogProposals)
	mux.HandleFunc("POST /dsh/catalog/proposals/{proposalId}/decision", protected.handleDecideCatalogProposalExpected)
	mux.HandleFunc("POST /dsh/catalog/proposals/{proposalId}/transitions", protected.handleTransitionCatalogProposalExpected)
	mux.HandleFunc("GET /dsh/catalog/policies", protected.handleListCatalogPlatformPolicies)
	mux.HandleFunc("PATCH /dsh/catalog/policies/{policyId}", protected.handleUpdateCatalogPlatformPolicyAtomic)
	mux.HandleFunc("GET /dsh/catalog/stores/{storeId}/assortment", protected.handleGetOperatorStoreAssortment)
	mux.HandleFunc("PUT /dsh/catalog/stores/{storeId}/assortment/{masterProductId}", protected.handleOperatorUpsertStoreAssortmentAtomic)
	mux.HandleFunc("GET /dsh/field/catalog/domains", protected.handleListFieldCatalogDomains)
	mux.HandleFunc("GET /dsh/field/catalog/nodes", protected.handleListFieldCatalogNodes)
	mux.HandleFunc("GET /dsh/field/catalog/master-products", protected.handleListFieldCatalogMasterProducts)
	mux.HandleFunc("GET /dsh/field/catalog/stores/{storeId}/assortment", protected.handleGetFieldStoreAssortment)
	mux.HandleFunc("PUT /dsh/field/catalog/stores/{storeId}/assortment/{masterProductId}", protected.handleLegacyFieldUpsertStoreAssortmentAtomic)
	mux.HandleFunc("GET /dsh/partner/catalog/domains", protected.handleListPartnerCatalogDomains)
	mux.HandleFunc("GET /dsh/partner/catalog/nodes", protected.handleListPartnerCatalogNodes)
	mux.HandleFunc("GET /dsh/partner/catalog/master-products", protected.handleListPartnerCatalogMasterProducts)
	mux.HandleFunc("POST /dsh/partner/catalog/proposals", protected.handleCreatePartnerCatalogProposal)
	mux.HandleFunc("GET /dsh/partner/catalog/proposals", protected.handleListPartnerCatalogProposals)
	mux.HandleFunc("GET /dsh/partner/catalog/assortment", protected.handleGetPartnerStoreAssortment)
	mux.HandleFunc("PUT /dsh/partner/catalog/assortment/{masterProductId}", protected.handleLegacyPartnerUpsertStoreAssortmentAtomic)

	registerUnifiedCatalogRoutes(mux, protected)
	return mux
}
